### ISSUE TITLE
Design a Payment for Receipt Zoe contract

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#1032]
Our ecosystem doesn't currently have good support for direct person-to-person payments.

Even getting connected to an object representing the right agent is problematic. The SharingService provides a mechanism for coordinating as long as two people have an out-of-band connection, but individuals still have to come up with an API that allows one of them to send payments to the other. 

We don't want a global registry, but it would still be helpful to have a standard mechanism that it would be easy for people to participate in.

But that opens issues with whether particular people or agents actually want to accept unsolicited payments. This can cause issues for accounting systems, exposure to conflict of interest charges, or just denial of service by having to handle payments not connected to known transactions.

One institution that seems to address this is offering payments in exchange for a receipt. The issuance of the receipt gives the intended recipient the ability to decline, and gives the payer something to connect the incoming funds to in their accounting system. 

My first fleeting thoughts are that the receipt itself might be a non-fungible payment where the contract maintains control of the Issuer, though I don't have a solution for how the "signer" of the receipt establishes an identity. Requiring everyone who wants to produce receipts to create their own unique Issuer also seems problematic.  

I'm inclined to move forward with a simple design in which someone offers money and can either specify the specific receipt they want, or only that there be a receipt, and Zoe enforces that the counter-party provide an appropriate receipt (which they can get from the contract, probably for free) before the exchange takes place. This corresponds to the informal case of receipts, where in many cases, a receipt is just a pattern of ink on paper.

**Comment by katelynsills** [comment]
I want to record the design that was mentioned during the meeting, so that we have a clear comparison (although we can have multiple competing different payment solutions simultaneously without problems - we don't have to chose one.)

I'm going to call this the "mailbox" registry. We can have an on-chain vat that allows users to register on-chain objects that must have a `receivePayment` method that accepts an ERTP payment. The `receivePayment` method could do a wide variety of things, including drop the payment, therefore declining it. It could only accept payments of a certain brand, or it could accept multiple brands. It could choose which purse to put it in based on various criteria. 

This is technically simple and doable right now, which is a huge plus. The downside is, because of ocaps and because this mailbox is public, we do not know anything about the entity we are receiving things from, and therefore our criteria for acceptance cannot be based on that. We can look at the public chain data and see which purse the payment originated from, and maybe which public key is identified with that transaction (?).

**Comment by katelynsills** [comment]
@Chris-Hibbert given that we have person-to-person payments in the wallet now, are you ok with closing this?

**Comment by Chris-Hibbert** [comment]
It's certainly not a blocker for anything we're going to need in the short term, but it still feels like a valuable contract we may want to build at some point. I don't think the payments supported by the wallet give the same functionality--we don't have any receipts or bookkeeping on sources of deposits, right?

If we're not using issues like this to track "potential contracts we might want to build at some point", then we can close the issuer, but it's not because we've satisfied the need.

**Comment by katelynsills** [comment]
I think we can close this, as users send payments using the boardIds for depositFacets in their wallet.
