### ISSUE TITLE
survey of testing frameworks

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#1335]
Our current unit tests use a combination of `tape` and `tap`. We started out using `tape` for both the test-runner (the executable that appears in the `package.json` entry for `yarn test`) and the test-execution library (the thing that gets imported at the top of each test file, like `import { test } from 'tape'`, and which gets invoke like `test(NAME, t => { assertions })`), and also as the assertion library (the code that provides `t.equal` and `t.throws` methods).

`tape` (the test-runner) *imports* all of the `test-*.js` files that you tell it to run, which means they all run in a single shared process. This doesn't work well with the way we set up SES, which requires exactly one `lockdown()` call at the beginning of the process. The `tap` test runner, on the other hand, runs each test file in a separate process. For that reason, when I ported the tree to the new SES API, I changed all the packages that needed SES to use `tap` as a test runner: this includes everything that needs swingset, or `harden`, or `import-bundle`. I left `tape` as the test-execution/assert library in many of those tests, partially because it reduced the size of the change, and partly because SES's `Error` taming made tracebacks unhelpful (which has since been fixed).

However we've found a lot of pain points in these libraries. My personal ones are:

* tests that involve a swingset are really slow, it seems to take a full second or two to start each one (I don't know if that's swingset's fault or something the test harness is doing to it)
* tests which emit significant text to `console.log` run really really slow, it feels like `tap` is rate-limiting stdout to perhaps 5 or 10 lines per second
* if a test fails in the middle of a long run, it's really difficult to find out what happened: there is a summary printed at the end of the test run that counts the errors, and it *might* tell you the file in which the failure occurred, but any assertion details or log messges surrounding the test are lost thousands of lines back in the scrollback, if your terminal even kept that many
* `tap` can run tests in parallel to compensate for the one-process-per-testfile slowdown, but so far I haven't seen this improve things very much, and it interleaves console output from all tests, making it even more impossible to find a failing test's output

So this ticket exists to solicit test-framework recommendations from our team. I only have experience with `tape` and `tap`, but I know we've got some experienced JS developers here who have favorites from other projects that I'd like to learn about. I know of `mocha` and `jest`, and will be investigating them, but please add notes with:

* other JS test frameworks you're familiar with, what you like/dislike about them
* problems you've had with our existing test framework that we should try to address
* use cases or features you've wanted to see added

refs #591 #903

**Comment by kriskowal** [comment]
Toward doing no worse than tap/tape:

* Test modules should be runnable with `node` in isolation without alteration. The output should probably be uncolored TAP so that it composes well with other tools, if it isn’t amazing on its own. This means avoiding TDD/BDD systems with that inject functions like `describe` and `expect` into global scope. This precludes Jasmine, Mocha, and Chai.
* Test runner should be able to parse and aggregate TAP such that tests that might not compose well with the test assertion library can elect to dump TAP to the console directly.
* Test assertion library should continue to work under SES.

Beyond status quo:

* It would be really nice to able to test a single case in isolation. The systems for testing Go build a binary out of a package’s tests and that binary takes command line arguments to run tests or benchmarks that have a description matching a regex.
* It would be nice for the migration process for existing tests to be as close to “Run this sed script” as possible (`ava` appears to qualify).
* Promises as first principles. There should be no need to mark the end of a test. Every test function returns a value that can be trapped in `Promise.resolve` and the test ends when that promise settles. If the test throws an exception or returns a promise that is later rejected, the test fails. (I rewrote Jasmine to this end, but it’s got that `describe/expect` DSL disease https://github.com/montagejs/jasminum).
* Should integrate well with a coverage system that merges the coverage results of all tests and generates a report that we can read from CI results.
* Should be able to step into an isolated failing test in a debugger.
* Should have a great story for benchmarking.

Most of my experience has been with `tap`, `tape`, or `jasmine` with `sinon`.

**Comment by warner** [comment]
@dtribble suggests looking at [Ava](https://www.npmjs.com/package/ava)

**Comment by erights** [comment]
Some pointers to test262:

https://test262.report/about

https://github.com/tc39/test262

https://bakkot.github.io/test262-web-runner/ runs the tests in your browser. Nice UI for navigating the tests.

**Comment by Chris-Hibbert** [comment]
I don't have much to say about JS testing environments. 

I do want to remind people of the discussions we've had about `t.plan()`. I don't know whether this has a high-enough weight in the discussion to sway any decisions, but it would be nice if there were a simple way to find out that a test written in a straightforward way didn't perform all the checks it was intended to. `t.plan()` is high maintenance, but in our current frameworks, we didn't find another approach that was sufficiently reliable to replace it.

**Comment by katelynsills** [comment]
My past JavaScript testing experience has been with Mocha and Chai, which I wouldn't necessarily recommend.

I've been interested in using Jest for personal projects, but I haven't assessed it for our current usage. I'd be happy to look into it further if that'd be helpful.

**Comment by erights** [comment]
A further test262 relevant pointer:

https://github.com/bterlson/eshost
https://github.com/bterlson/eshost-cli

the `eshost` framework test262 uses to run the same tests on a great variety of JS platforms, including servers, XS, and browsers.

**Comment by FUDCo** [comment]
Running tests in parallel definitely should never result in the different tests' output being interleaved.  That just seems like lazy engineering.  The lack of attention to output ergonomics in pretty much every test framework I've used is appalling.  This is especially surprising in that a lot of these libraries have clearly invested a great deal of care on the ergonomics of writing the test assertions themselves, so it's not like this stuff is just being tossed off by people who don't care to make an effort.

The thing I've found most consistently aggravating across frameworks is the difficulty of correlating test assertion outputs with the code generating them.  When I'm trying to diagnose a test failure I frequently find myself resorting to inserting a print statement prior to each and every test assertion.  Perhaps just having a framework that's able to reliably produce accurate line number information would deal with this; I'm not sure why this is such a common issue but it observably is.

It's certainly been my experience that the overwhelming majority of fixes for test failures consist of changes to the tests rather than changes to the code being tested, simply because a minor but correct change in the behavior of the code under test often invalidates the test.  It's still valuable to force the developer to confront the change in behavior and make an explicit assessment as to whether the new behavior is actually correct or not, but it does hint that a lot of tests are asking "does this code do the same thing it used to do?" rather than "does this code do the right thing?".  This in turn makes me wonder if we are writing a lot of tests at the wrong level of abstraction and to further wonder if the tools are biasing us into doing this.

**Comment by FUDCo** [comment]
Being able to run individual tests in isolation is tremendously useful -- I'd deem it essential, actually.  I do find the tape/tap `test.only` idiom enraging, however.  First, because it only lets me select a single test, and if I've got like 4 out of 263 tests that are failing I'd like to be able to selectively rerun just the 4.  Second, because it requires me to edit the code to control selective execution, which aside from being an annoying inconvenience exposes me to the risk that I'll accidentally check in some code with tests disabled.  Tests should be individually named and the test runner should be parametrizable using those names (and those names should appear in the test output also).

**Comment by dtribble** [comment]
## Basic testing requirements
1, assert library should be straightforward JS, not the "DSL" wackiness of "assert(result).shouldBe(3).except("thursday")".
1. run all tests and report failures
1. get enumerated test failures at the end
1. be able to rerun failing tests
1. run a subset of tests:
-- single test file, across packages, files,. and specific tests within files (without having to set "only" as an edit in the file)
1. optional run coverage
1. optional run benchmarks
1. integrate with CI
1. VSCode/WebStorm test integration so you can easily rerun individual tests in their UI
1. shared test jigs
1. FAST
1. separate test suites, so smoke tests and long-running tests are separate
1. console output should be recorded with the test case

## Good to have
1. run tests in parallel
1. run across multiple packages (rather than getting multispawned by Yarn/Lerna)
1. track coverage associated with individual test (files)
1. test order randomization to detect order dependencies
1 test results and console from each test should be available but optional
1. supports frontend tests (e.g., browser simulator, possibly using specific extensions for that)

..to be continued but saving in case of more crashes!

**Comment by dtribble** [comment]
It's worth noting that assertion library and test runners are potentially indepedent

## System thoughts
### tape/tap
- decent assertions
- tape: Slow
- terrible reporting
- can't rerun failing tests
- poor test control

### Mocha et al
- wacky assertion library

### [Ava](https://www.npmjs.com/package/ava)
Only looked at the docs in research, haven't used
- interesting assertion library (power assert)
- multiproject concurrent testing
- coverage support

## NOT JS, but listed for comparison about where the bar should be

### Ruby/Rails testing libraries
- always reports failing tests
- supports rerunning failed test
- awful DSL for assertions

### Midori
- test *cases* are tracked in DB across test runs
- concurrent test execution across individual tests (not just files) with separate failure tracking/reporting
- distributed test runs

### MS Exchange
- test UI integrated with CI to compare local vs. CI
- coverage per test case, with basic-block dependency tracking to only re-run test affects by a change
- distributed test runs including multiple machine configurations

**Comment by dtribble** [comment]
@kriskowal 
> * Test modules should be runnable with `node` in isolation without alteration

What does this mean?  In particular, it would seem well satisfied by: 
```
yarn test test-foo
```
or 
```
yarn test test-foo:16 test-bar:"deposit-only"
```

Or other controls to run specific test files and/or test cases.

**Comment by warner** [comment]
My interpretation (and preference) is that you can run `node (something)` and some tests will run, rather than only being able to run `test-tool (name of test to run)`. The former gives me a stronger sense of control: I know I can use `node` options like `--inspect-brk` (rather than relying upon `test-tool` to pass through whatever subset of `node`'s options they thought I might want), I could run `endo (something)` instead of `node (something)` and get something useful out of it. Plus I know that whatever I'm printing to the console will actually make it to stdout where I can see it, and won't get hidden by a test tool that's trying to declutter my terminal.

I believe there are plenty of higher-level features that can only be had by running `test-tool (stuff)` to drive tests in the normal case, but I think the ask here is to additionally/optionally be able to run a single file's worth of tests by just running the file as a normal Node program and be able to see enough of the output (maybe just TAP-formatted "ok" / "not ok" lines) to tell that it worked, or what exactly failed.

I guess my preference would be for a `test-tool` that runs a bunch of programs in parallel, gathers their results and console output in a sensible way (maybe hiding the output for passing tests, storing and re-emitting the failing ones at the end, or in a file where I can ask for them afterwards), and prints a summary result. *But*, if I'm trying to diagnose something, I want that `test-tool` to get out of the way while I just run a normal program.

**Comment by warner** [comment]
>     11\. separate test suites, so smoke tests and long-running tests are separate

@dtribble does this mean more than one top-level command, that run separate subsets of the overall tests? Like `yarn test` and `yarn test-integration` and `yarn test-everything`? Are you thinking that maybe each test should be marked as to which category it falls into, or we should have special directories like `packages/zoe/test-slow/` vs `packages/zoe/test/` and the top-level commands know what those mean?

**Comment by Chris-Hibbert** [comment]
At google, tests could be annotated `@small`, `@medium`, and `@large`. In addition to allow one to run only rapid tests during TDD, the system also monitored the run times, and interrupted small and medium tests that ran too long and declared them to have failed.

**Comment by dtribble** [comment]
I'm fine with any of several mechanisms for separating unit/integration/etc. tests. Separate files/directories is pretty typical and easy -to-manage.

In systems with actual test case management, the test cases are extracted int a tool that can separately designate tests cases as in various suites. I think we would rather have it obviously based on what file it's in.

**Comment by dtribble** [comment]
WRT the `node some-testfile` I think that's at best the lowest priority, and more likely just the wrong thing to try for. Make the test-tool invocations something you can actually trust or get another tool! 

As it is, you have to know magic like `-r esm` (or worse) to make it work. Why is `node ...` special as opposed to e.g., `./some-test` or `sh some-test`. Testing is important. We should use a tool that actually supports it rather than something the wedges test execution, scheduling error reporting, etc. into a vm afterthought with just slow output streams.  I'm fine if that accidentally or easily happens (e.g., with the right "#!") but to me it's mostly shackles that impede deploying a good tool

**Comment by dtribble** [comment]
Ava notes

I did some trials of the Ava testing library.  I made some broad search/replace to address some common patterns of differences in the assertion library, and then dug specifically into the ERTP library to look at promise differences and some timing.  

Here are timings for just ERTP
Using TAP:
```Suites:   6 passed, 6 of 6 completed
Asserts:  377 passed, of 377
Time:     7s
Done in 7.68s.

real    0m8.046s
user    0m7.750s
sys     0m2.625s```

Using Ava: 
```
28 tests passed
Done in 4.17s.

real    0m4.531s
user    0m6.250s
sys     0m2.906s```

**Comment by dtribble** [comment]
One of the biggest overall differences is that it Ava doesn't let you get sloppy about promises. We use patterns that do eventual sends without waiting for the result, and then use a `plan` to check for whether they ever finished.  That would be bad style in normal programming, and in seeing several examples, that seems bad for tests.  There was no question in my mind the test expressions without that are less clear, may not test what we think (because items happen out of order), and make poorer examples. With Ava, promises must roll up to the return result of the method. 

Ava had a nice analysis of when to use plan. https://github.com/avajs/ava/blob/master/docs/recipes/when-to-use-plan.md  I followed that pattern in converting ERTP tests and it seemed better.  Many of the cases where plan might be needed evaporate when constructing test either with full promise wiring or more reliably, using await.  The reason why await is actually great here is that in general, you want tests to be sequential, except when you are testing something specifically pipelined.

I added #1447 to explore test differences. I recommend turning off whitespace for comparison, sicne indentation differences are irrelevant. https://github.com/Agoric/agoric-sdk/pull/1447/files?diff=unified&w=1

An example of psurious test overhead removed is:
https://github.com/Agoric/agoric-sdk/pull/1447/files?diff=unified&w=1#diff-c46fc84dcf32a300b154a29226e53af1L387. If a test throws during execution, of course the test should fail.

An example of ignoring promise results and having to make sure the assertion was checked anyway is: https://github.com/Agoric/agoric-sdk/pull/1447/files?diff=unified&w=1#diff-5fa60e98a7f71f0fe78d3b5283aee64dL24. The conversion of the tests to `await` was strictly superior because most such tests just unwound into a single obvious thread of control. In such tests, `plan` can and should be removed (see above article).  Net result was 20% code reduction and increased clarity for the few tests that had this pattern.

**Comment by michaelfig** [comment]
We will probably want to create our own library of utility functions that help adapt the testing tool we need to our requirements.

The thing I dislike about tap/tape is the clever idea of using stdout to report the results of the tests, and their accompanying abysmal handling of tests that generate output other than the `ok` / `not ok` required by them.

If we go to a test system that has a fancy runner, I'd like to go all the way, and get the runner that is clearly best.  If the tests we write using that system are simple enough to be portable between runtimes (that is, the assertion library is lightweight enough to stub under, say, XS) then we will have a clear win.
