### ISSUE TITLE
[Zoe] UserSeat.exit() and ZCFSeat.exit() should have same behavior?

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1421]
**What is the Problem Being Solved?**

@erights had previously said that if `UserSeat.exit()` and `ZCFSeat.exit()` had the same name, they should have the same behavior. In other words, if `UserSeat.exit()` is present, the seat should be exited without condition, like `ZCFSeat.exit()`. At the time, we thought that feature testing `UserSeat.exit()` would work. But @dtribble pointed out that `UserSeat` will be a presence and feature testing doesn't work on presences. The current state of `zoe-release-branch` is that `UserSeat.exit` always exists but may or may not exit. 

We need to determine if this behavior is acceptable, or if there is a better solution.

**Comment by dtribble** [comment]
Since
- the client made the offer
- the "exit" option is part of the proposal that's available on the seat

The client can be reasonably expected to eitehr know by contruction or find out what exits are possible. Thus, there's no loss of function if calling `exit` on a `userSeat` throws (rejects the result promise) if it's invoke on a seat that cannot exit.  

There are exit cases (not currently supported) that are optional (e.g., "waived" or "only after a time but not automatic"), so alternatively it returns a boolean as to whether exit was allowed.

**Comment by erights** [comment]
> The client can be reasonably expected to eitehr know by contruction or find out what exits are possible. Thus, there's no loss of function if calling exit on a userSeat throws (rejects the result promise) if it's invoke on a seat that cannot exit.
>
> There are exit cases (not currently supported) that are optional (e.g., "waived" or "only after a time but not automatic"), so alternatively it returns a boolean as to whether exit was allowed.

But this is a major semantic difference between the two `exit` methods. When the user is not allowed to exit using the userSeat, the contract can always the zcfSeat. Since we can't use feature testing to avoid this divergence, I still think they need different names.

**Comment by katelynsills** [comment]
For the different names, what about `userSeat.attemptExit()` or `userSeat.tryExit()`? The fact that it may not be successful is the only semantic difference, so I think attempt/try captures that

**Comment by erights** [comment]
Prefer `tryExit, but I'm good with either. Thanks.

**Comment by katelynsills** [comment]
Renaming to `tryExit` on the UserSeat
