### ISSUE TITLE
assertProposalShape sounds like the assert happens now rather than in future

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1565]
See https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r470933959 for context and comment from @dtribble

**Comment by Chris-Hibbert** [comment]
assertKeywordsWhenProposal, assertKeywordsWhenProposed (ick).  I like adding "When", but I haven't come up with anything that isn't too long for my taste.

**Comment by erights** [comment]
Is this about `assertProposalShape`? (which used to be named `assertProposalKeywords`, but that was confusing because it was checking property names that included non-keywords)

If so, I suggest that the relevant distinction is not immediate vs eventual. Generally and `assertFoo(...)` call tests something. Here, we have a combinator over offerHandlers. It takes an offerHandler and returns a checking offerHandler that wraps the original one.

**Comment by katelynsills** [comment]
Yup, this is about `assertProposalShape`.

**Comment by erights** [comment]
`guardedHandler`?

**Comment by katelynsills** [comment]
is the maker function itself called `guardedHandler`? I could see that being a good name for the returned function. Should it be `makeGuardedHandler` or `guardHandlerExactly`?

**Comment by erights** [comment]
How about just `guardHandler` returning a guardedHandler?

**Comment by erights** [comment]
Hmm. I said `guardHandler` thinking of "guard" as a verb. But it invites a confused misreading as an adjective modifying "Handler".

Perhaps there's a verb line "guard" that better avoids this misreading?

**Comment by erights** [comment]
Otherwise, I think `makeGuardedHandler` is best.

**Comment by dtribble** [comment]
Looking at code for this, it's no longer buying us much to have this as a wrapping handler rather than having it be something that the handler puts as its first line of code:
```
function buyHandler{seat) {
    seat.assertShape(...);
    const { give: {...} ...} = seat.getProposal();
...
```

Positives:
The motivating secondary benefit for this more direct approach is that the "parameter keywords" are more obviously visible in the definition of the handler.

It's easier to drop a breakpoint into an inline asset than a helper.

Negatives:
The is not quite ideal because it's operational rather than declarative about the required shape. So some more options might be nice to consider.
