### ISSUE TITLE
cosmic-swingset probably drops outbound mailbox messages during partial-commit interruption

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#1605]
**Describe the bug**

https://github.com/Agoric/agoric-sdk/pull/1604#pullrequestreview-473684144 describes a problem I studied while reviewing a change to the way cosmic-swingset manages our two commit points. When we receive END_BLOCK, swingset commits its own state first, then cosmos-sdk commits the rest of the cosmos state. The `block_manager.js` code in that PR correctly manages the three situations that might occur:

* swingset commits, cosmos commits, process survives to the next block
* swingset commits, cosmos commits, process dies. At restart, both resume where they left off.
* swingset commits, process dies. At restart, swingset is one block ahead of cosmos, and tolerates replay.

However I think the way we're managing the "mailbox state" leaves a gap in that last situation, and outgoing mailbox messages sent during that block will be dropped.

The mailbox state is kept in a simple `Map` that is modified by the mailbox device, and read by the host code during calls to `saveChainState()`. This function copies outbound messages (and the `ackNum` which indicates which inbound messages have been seen) into the cosmos state vector. The initial contents of this `Map` come from the cosmos state vector: they are copied from the cosmos Keeper into the `Map` each time the process starts up.

When we hit the third situation described above, there will be some block N whose inbound actions provoked a new outbound mailbox message. The `Map` will contain this outbound message, and we'll call `saveChainState()` to copy the N-message into the cosmos keeper, where it will sit until cosmos reaches its commit point (spoiler alert: it never does). Then swingset calls `saveOutsideState()` to commit the swingset N-state, as well as the list of actions which got us to state N. Then the process dies.

At startup, the cosmos state (including the mailbox contents) will be for block N-1, but the swingset state (and saved actions) will be for block N. Cosmos will restart from N-1 and replay all the transactions for block N. Swingset will notice that it's receiving a BEGIN_BLOCK/DELIVER_TX/END_BLOCK for N, and that these actions match the ones that were saved, so it will ignore them. After it finishes ignoring the END_BLOCK for N, it knows the current in-memory swingset state (unchanged since the replacement process launched and loaded it from disk) matches the old in-memory state that was present in the previous process just before cosmos managed to commit. At that point, swingset is up-to-date.

However, the mailbox Map came from the cosmos state, which was loaded from N-1. And because we skipped all the swingset transactions, we never re-invoke the mailbox device to regenerate those outbound messages.

So I think the consequence is that any outbound mailbox messages generated in a block for which swingset commits its state but cosmos does not, will be dropped and never recreated.

I suspect the fix will be to include a full copy of the mailbox Map in the mailbox-device state (which is stored in the swingset state vector), as well as in the cosmos state vector (where downstream followers can see it, which is how ag-solo currently receives messages from the chain). The mailbox device should copy this into the external (i.e. cosmos) table once at startup time, and then again after every time the device is invoked (for new messages). We should probably *not* copy the starting cosmos state into the mailbox state. Instead, the mailbox device should treat the cosmos-side table as a pure output.

We clearly need a good test of this, which will involve some means to manually interrupt the chain after swingset has committed but before cosmos gets to commit. Then we restart the process from those commit points and see if the new cosmos state knows about the outbound message.

**Comment by michaelfig** [comment]
The mailbox state goes through the same `chainSend` function that all SDK calls do.  All that we need to do is persist the `savedChainSends` when saving the kernel DB, and recover them from there when the process restarts.  I was mistaken in thinking that this persistence was already done.

On `END_BLOCK`, if we are recovering, we already do `flushChainSends(true)` to replay the `savedChainSends`.

**Comment by michaelfig** [comment]
Yeah, it looks more complicated than that.

**Comment by michaelfig** [comment]
I'd like to clean up the mailbox handling in general: right now the mailbox is never actually loaded from the chain state because the load attempt happens before the chain has initialised.  Also, it attempts to load a record representing all of the mailboxes at once and then never again.

I'd rather put a JS (i.e. swing-store API) caching layer in front of the on-chain mailbox manipulations, and have only the mailbox of interest fetched on demand and updated in memory.  Then, flushing the cache out to the chain only to the individual changed mailboxes can happen all at once at the end of END_BLOCK.  It would be a good time also to get rid of the "all mailboxes" on-chain storage key, which won't scale to zillions of mailboxes.

That would put an upper bound on the chain interactions (only one read and write per changed mailbox per block).  It would reduce the Merkle tree burden (no "all mailboxes" key) and JS memory use.

I'd also simplify the "x/swingset/egresses" implementation not to require a separate storage.  Then we could solve all the chain state issues in one fell swoop, by using just the "x/swingset/storage" abstraction, exporting it and importing it on upgrade, and interacting with it with a simpler cache architecture (using arbitrary `savedChainSends` on replay) than the existing JS mailbox cache.

Thoughts?
