### ISSUE TITLE
Standardize assertUniqueKeyword Error Messages to reveal keyword or not

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1700]
**What is the Problem Being Solved?**

Depending on why an error is thrown, the error messages differ in whether the keyword is printed or not:

```js
  t.throws(() => zcf.assertUniqueKeyword('B'), {
    message: 'keyword (a string) must be unique\nSee console for error data.',
  });
  // Unique, but not a valid Keyword
  t.throws(() => zcf.assertUniqueKeyword('a'), {
    message:
      'keyword "a" must be ascii and must start with a capital letter.\nSee console for error data.',
  });
```

**Description of the Design**

Standardize whether keywords are revealed. I think we should reveal them.

**Security Considerations**

Keywords will be revealed in more cases than previously.

**Test Plan**
The ZCF Tests we are writing is how I found this discrepancy, so they should be used as the tests to measure this change.

**Comment by erights** [comment]
The first case is ***NOT*** hiding the keyword. As it says `'See console for error data.'` The first case only hides the keyword from calling code or any other code with access to the error object. The keyword itself is being sent to the log. That's the whole point of the `assert` module splitting what's revealed to calling code vs what's revealed to those that can see the log. Human programmers will generally be able to see the logs they are concerned about. Other than informing humans of diagnostic info, code should never care whether the keyword is revealed in the error message shown to code. The only code that would care would be code that scrapes the error messages to find the keywords. No one should write such code.

Unfortunately, this error data currently appears in the log output physically distant from the logging of the thrown error. https://github.com/Agoric/SES-shim/issues/440 should fix that by Alpha.

All that said, I agree that keywords should be revealed consistently using `q`. This is not the kind of thing that anyone reading or writing the code would expect to be secret. 

This kind of explicit declassification is what `q` is for. https://github.com/Agoric/SES-shim/issues/440 takes the pressure off dangerous declassification, since the inconvenience penalty of not declassifying will be vastly reduced to anyone with access to the logs. But we still should not worry about explicitly declassifying keywords.

**Comment by katelynsills** [comment]
@erights, I think you are misunderstanding what I said. I am talking specifically about the error message which is what the assertion tests, not about the logging. So in the context of the error message only, the keyword is hidden. 

And yes, I believe one of these case uses `q` so it is a matter of making it consistent.

**Comment by erights** [comment]
Ah good point. The test checking the error message is indeed a third category. Such tests should care what diagnostic info is generated for humans to look at. If we're not careful, our desire to have tests check that would create pressure to reveal in error messages info that is useful for humans, and that should be hidden from normal code. Therefore, tests need to be able to check diagnostic info that is not revealed to normal code. Therefore tests need special powers.

See
https://github.com/Agoric/SES-shim/blob/console/packages/console/test/throwsAndLogs.js
and its uses at
https://github.com/Agoric/SES-shim/blob/console/packages/console/test/assert.test.js

`throwsAndLogs` is like `t.throws` but also tests the diagnostics revealed only to the log. And it checks the actual data, not just the stringified form of the data.

Note that all this is aside from the immediate question about keywords. Those should just be explicitly declassified with `q`.

**Comment by erights** [comment]
> @erights, I think you are misunderstanding what I said. I am talking specifically about the error message which is what the assertion tests, not about the logging. So in the context of the error message only, the keyword is hidden.

Other than overlooking the special needs of test code, if you think I'm still misunderstanding something, please explain.

**Comment by erights** [comment]
Attn @dckc this is how the E concern with error sealing is showing up again.

**Comment by katelynsills** [comment]
Closed in https://github.com/Agoric/agoric-sdk/commit/1fa44d9ff7c7f8b317df442ba7a5893a95e49f7b
