### ISSUE TITLE
Feature: weakref-based cleanup

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#20]
Proposed by @erights as an optional feature.

**Comment by zarutian** [comment]
https://tc39.es/proposal-weakrefs/ is of intrest to those issue readers who do not know how that would work.

In short. A FinalizationRegistry would be used to keep track of if presences local to a vat yet pointing into remote vats have been locally gc'ed. If so we can inform the remote vat of our disintrest into the object that had been referenced.
(Do not ask about object graph cycles of garbage that span multiple vats. That problem is not only thorny, it is an entire briar patch. (self-memo: staleness-colouring via vat-vectorclock-timestamps))
