### ISSUE TITLE
Seats should be created along with invitation

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#2007]

**Comment by zarutian** [comment]
I am guessing you mean the zcfSeat for an invitation should get created when the invitation is created and not when the offerHandler given to .makeInvitation() runs.

Now the question becomes, how should that zcfSeat be accessable prior to the offerHandler running?

**Comment by Chris-Hibbert** [comment]
The proposal is that there be an alternative to `zcf.makeInvitation()` that also returns a zcfSeat, like the ones from `zcf.makeEmptySeat()`  

The reason this seems useful is that in the call-spread contract, the contract had to create promises for the seats that wouldn't be allocated until the `offer()` call, in order to allocate to them, even though the `offer()` call could be much later.

This means that the initial allocation would be empty, and when `offer()` is called, we need to add to the allocation, and detect that the seat has already been created and wired up.

**Comment by Chris-Hibbert** [comment]
We decided not to pursue this issue any further because of inherent race conditions it raises in managing allocations and deposits between zoe and zcf.
