### ISSUE TITLE
Need to suppress UnhandledPromiseRejection handling generically, for both Node and Ava

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#2030]
See #2023 and #2029 

It is unpleasant to have the `.catch` calls scattered around our code. The Node UnhandledPromiseRejection handling is inappropriate in general for our platform, since 
   * remote messages produce promises whose intended rejection handling behaviors cannot be registered in the same term.
   * Node's behavior enables any code to terminate the Node process as a whole.

Once we have fixed this issue generically, we should go back and remove the scattered `.catch` calls that litter our code for only this purpose.

**Comment by erights** [comment]
Before suppressing UnhandledPromiseRejection, we also need to provide alternate diagnostic that serves approximately the original need better, but without the above problems.

Attn @kriskowal @michaelfig

**Comment by michaelfig** [comment]
For clarification:

> * remote messages produce promises whose intended rejection handling behaviors cannot be registered in the same [turn].

That's not entirely true.  If a vat returns a rejected promise to a caller in another vat, then a `.catch` handler is registered on the original promise (by liveSlots) in the same turn.  When such a rejection is conveyed via the SwingSet kernel, it arrives on the sender's side long after they had a chance to register a handler. The problem is when the original promise is rejected, but not sent to liveSlots in the same turn.

But to your point, we could solve this for most of our uses by having `makePromiseKit` attach a no-op `.catch` handler.  Solving it completely can only be done if we can control platform promises somehow.

> * Node's behavior enables any code to terminate the Node process as a whole.

Not quite.  The default Node behaviour (currently only a warning) is used only if there is no explicit `UnhandledPromiseRejection` callback.  SwingSet explicitly adds a callback that itself prints a warning, which means the process will not be automatically terminated.

Ava is much less tolerant (and will probably require a fork to fix), since it insists on reporting any `UnhandledPromiseRejection` callback invocation as a test failure.  It does this even if there is already an explicit callback attached.

The only benefit of our explicit `.catch` handlers is to prevent *all* `UnhandledPromiseRejection` callbacks from running.

> Once we have fixed this issue generically, we should go back and remove the scattered `.catch` calls that litter our code for only this purpose.

Agreed.

**Comment by erights** [comment]
@kriskowal @mhofman @michaelfig you guys did this, right? If so, please close. Thanks.

**Comment by kriskowal** [comment]
Yes, this should be addressed and if there’s any further work, it would be a defect with a new issue.
