### ISSUE TITLE
Tests with nodejs v14.15.2 fail on `master`

### ISSUE THREAD

**Issue by dtribble** [Agoric/agoric-sdk#2097]
**WORKAROUND**
Run with `node v14.15.1` or lower.

**Describe the bug**
Creating a new build environment from scratch against nodejs version `v14.15.2` or later fails.  `yarn test` fails in `tame-metering`, as does any attempt to `agoric start` in dapps.

```
> @agoric/tame-metering
$ ava

  istamed › isTamed

  Error thrown in test:

  TypeError {
    messageundefined'Cannot redefine property: constructor',
  }
```

**To Reproduce**
1. sync master
2. `yarn; yarn build`
3. `yarn test`

**Expected behavior**
Tests pass

**Platform Environment**
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

**Additional context**
The full context:

```
> @agoric/tame-metering
$ ava

  ✖ No tests found in test/test-sanity.js

  ─

  istamed › isTamed

  Error thrown in test:

  TypeError {
    messageundefined'Cannot redefine property: constructor',
  }

  › defineProperty (<anonymous>)
  › assignToTarget (src/tame.js:243:11)
  › src/tame.js:256:7
  › Array.forEach (<anonymous>)
  › Array.forEach (src/tame.js:172:20)
  › wrap (src/tame.js:255:40)
  › wrap (src/tame.js:226:7)
  › wrapDescriptor (src/tame.js:67:20)
  › assignToTarget (src/tame.js:239:19)
  › src/tame.js:256:7

  Uncaught exception in test/test-sanity.js

  TypeError: Cannot redefine property: constructor

  › TypeError: Cannot redefine property: constructor
  › defineProperty (<anonymous>)
  › assignToTarget (src/tame.js:243:11)
  › src/tame.js:256:7
  › Array.forEach (<anonymous>)
  › Array.forEach (src/tame.js:172:20)
  › wrap (src/tame.js:255:40)
  › wrap (src/tame.js:226:7)
  › wrapDescriptor (src/tame.js:67:20)
  › assignToTarget (src/tame.js:239:19)
  › src/tame.js:256:7

  ─

  1 test failed
  1 uncaught exception
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.`
```

**Comment by dtribble** [comment]
@michaelfig proposed taht a new property was made non-configurable, and suggested 
> commenting out the `throw e` in `packages/tame-metering/src/tame.js:247` 

That got me pat the issue and everything works.

**Comment by dtribble** [comment]
Clearly introduced in node v14.5.2:
```
tribble@Alien:~/dev/agoric-sdk/packages/tame-metering$ nvm use v14.15.1
Now using node v14.15.1 (npm v6.14.8)
tribble@Alien:~/dev/agoric-sdk/packages/tame-metering$ yarn test
yarn run v1.22.5
$ ava

  3 tests passed
Done in 0.50s.
tribble@Alien:~/dev/agoric-sdk/packages/tame-metering$ nvm use v14.15.2
Now using node v14.15.2 (npm v6.14.9)
tribble@Alien:~/dev/agoric-sdk/packages/tame-metering$ yarn test
yarn run v1.22.5
$ ava

  ✖ No tests found in test/test-sanity.js

  ─

  istamed › isTamed

  Error thrown in test:

  TypeError {
    messageundefined'Cannot redefine property: constructor',
  }
 ...
```

**Comment by erights** [comment]
Any idea which `constructor`?

**Comment by dtribble** [comment]
It's slightly faster to repro by just running `yarn test` in `agoric-sdk/packages/tame-metering`

**Comment by erights** [comment]
In the case where it throws
```js
        try {
          defineProperty(o, p, newDesc);
        } catch (e) {
          // Ignore: TypeError: Cannot redefine property: Symbol(Symbol.hasInstance)
          if (typeof p !== 'symbol' || !(e instanceof TypeError)) {
            throw e;
          }
        }
```
the value of `o.constructor` prints as `class SafeMap extends Map {}`. Any idea what `SafeMap` is? Is it one of our's? I could not find it grepping our code. Attn @michaelfig

**Comment by michaelfig** [comment]
> the value of `o.constructor` prints as `class SafeMap extends Map {}`. Any idea what `SafeMap` is? Is it one of our's? I could not find it grepping our code. Attn @michaelfig

Not ours.  Either Node's or v8's.

**Comment by erights** [comment]
The path is `globalThis.console._times.constructor`.

What is `_times`?

**Comment by warner** [comment]
I found `SafeMap` in the Node.js delta from 14.15.1 to 14.15.2: https://github.com/nodejs/node/commit/568e6177c9 . From what I can tell, they're stashing a number of primordials early (just like we do in SES) to defend against the application changing them at runtime. This patch started using a stashed `SafeMap` in preference to the normal `Map`. It wasn't clear how `SafeMap` is defined (it's extracted from something named `primordials`, but that must be something magic, because it doesn't appear as an import, and isn't part of the usual globals).

@erights says the core problem here is that `tame-metering` is taming too much: it modifies things which won't ever be exposed to a non-start-compartment. Also, tame-metering is happening before we `import 'ses'`, which means SES-shim is going to modify primordials that were metering-tamed without any coordination. I'm fuzzy on what he said the fix would be, but I do remember him saying that `tame-metering` should really be aware of the SES whitelist.

I *think* that means this gets kicked over to @michaelfig , since the fix needs to happen in tame-metering.
