### ISSUE TITLE
Rename purse `getCurrentAmount` to `getRecentAmount` and deprecate `getCurrentAmount`

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#2100]
**What is the Problem Being Solved?**

The notion of a "current" amount is not very useful when purses typically are in separate vats, since the returned value may be stale after the turn that sent it has passed.  If we relax "current" instead to be "recent", it sets user expectations to be just useful information about past balances instead of some kind of instantaneous truth.  This is especially true because `getCurrentAmountNotifier` is already lossy.

Relaxing the name allows us to implement windows into remote purses with consistent balances whose observation may be delayed.

**Description of the Design**

1. Change `getCurrentAmount` to be `getRecentAmount` and `getCurrentAmountNotifier` to be `getRecentAmountNotifier`.
2. Deprecate the old names.

**Security Considerations**

Consumers of the purse API must not rely on the instantaneity of the reported balance.  We hope that by changing the names, this requirement will be better communicated.

**Test Plan**

TBD.

**Comment by michaelfig** [comment]
@erights, @katelynsills, PTAL.

**Comment by erights** [comment]
PTAL the edited comment at the top of this thread? LGTM, thanks.

**Comment by katelynsills** [comment]
Looks good to me as well!

**Comment by erights** [comment]
Given these names, we should change the methods into `async` methods to ensure eventual use even in the local case. This prevents some local-synchronous usage that is useful in theory, such as in the zcfMint. But I just grepped and we make no such use from our non-test code.

**Comment by erights** [comment]
At #2109 I only made the `get*Amount` methods async. The `get*AmountNotifier` methods already return a notifier, which is eventual enough. No need to promise-ify it.

**Comment by Chris-Hibbert** [comment]
While I can see that `getRecentAmount()` has reasonable semantics for the caller, I think consideration of the present version of `getCurrentTimestamp()` would push us in the opposite direction. If we're okay applying different reasoning to the two situations, then I'm kinda okay with that decision, but if we think the argument for "recent" instead of "current" applies generally across a distributed system then I'm going to push for "current".

I think the semantics of `timerService.getCurrentTimestamp()` are what we want from a timerService. i.e. "please tell me what time it was when you received my request."  I think callers understand that when they receive it, it will necessarily be out of date, but they can't do any better than that from a distant time source. Calling it `timerService.getRecentTimestamp()` would not be a reasonable API in my opinion. Why doesn't the same argument apply for any other remote request for the most up-to-date state?  "Please tell me what the state was when you received my request."

**Comment by erights** [comment]
I like explaining the semantics as "please tell me what time it was when you received my request". I find the term "current" suggest something dangerously stronger than that. "recent" something weaker. The time case does make clear that "recent" suggests a semantics that is painfully weaker. From the caller's pov, the relevant guarantee is "Sometime between when I asked and when I got the answer." I would love a short simple term that successfully suggests that but have not found one.

**Comment by erights** [comment]
In ERTP at least, the term Current or Recent, whatever we call it, is not noise because the *only* thing that mutates both up and down and over time is the balances of purses. Everything else is either immutable or makes a one-time monotonic state change (payments getting used up). This is also why we could do pipeline-friendly data-flow ordering (wait for arguments) everywhere in ERTP except the deposit method.

**Comment by Chris-Hibbert** [comment]
As I understand it, the reason we originally moved from `getAmount()` to `getCurrentAmount()` was in response to the fact that it was the only query that retrieved a result that varies over time. That's a different consideration than reminding the user that the value may be out-of-date by the time they receive it. I think the latter is less important.

Can we gain anything by playing on people's instincts about food and freshness? When you buy produce you want it to be fresh at the store, but everyone realizes that it's less so once you get it home.  `getFreshAmount()`.  

I think `getThenCurrentAmount()` is closer to the semantic you're describing, but I think it's a terrible name. I'm not convinced that the API should try that hard to remind people that information takes time to propagate.

Most of this comment should be taken in the spirit of brainstorming rather than as a stake in the ground.

**Comment by dtribble** [comment]
I agree that "recent" is better than "current". My concern is that the argument for "it could have changed by now" is true for all mutable state on all far objects. That's not a bad as it could be because we try to mostly have immutable or monotonic values. But all remote values should be considered "possibly changed" so it's expensive and dulling boilerplate, where the actual content difference is being hidden by the `getRecent...`. 

-  `zcf.getRecentTerms()`
- `zoe.getRecentBrands`
- `vault.getRecentDebtAmount()`, `vault.getRecentCollateralAmount()`, `vault.getRecentCollateralRatio()`
- `treasury.getRecentCollaterals()`
- `amm.getRecentInputPrice()`, `amm.getRecentOutputPrice()`

So I recommend that either `getCurrentAmount` be made `getAmount` or `getBalance`, or if we do this, we do not presume it's a pattern, and Purse is special because it's ERTP.

I really like Chris's point:
> "Please tell me what the state was when you received my request."

**Comment by dtribble** [comment]
> Given these names, we should change the methods into `async` methods to ensure eventual use even in the local case. This prevents some local-synchronous usage that is useful in theory, such as in the zcfMint. But I just grepped and we make no such use from our non-test code.

This seems like a downgrade. Right now I can have a local purse where I check a value and then do something (ask how much there is and then withdraw all of it). If it's async, I can never do anything based on the balance. It can only ever happen is you have a local purse. Otherwise you must use `E`, so there is never an ambiguity as to whether it's allowed, so there's no actual confusion about what could be returned. Eliminating the local usage seems to add no value, but clearly eliminates some usage. Now this particular place might not matter, but the general expectation for such APIs is that there may be operations that do something synchronously if invoked synchronously. Eliminating all of those would be an enormous complexity increase (because you could never have single-turn methods, methods on an object reusing each other couldn't do so within a single turn, etc.). Thus there isn't a good general pattern here so applying it to a particular case seems bad.

**Comment by tyg** [comment]
For what it's worth, if we don't go with "recent" or equivalent, I can add to the relevant docs a quick mention of the time issue.

**Comment by katelynsills** [comment]
Closing as we have decided not to make this change
