### ISSUE TITLE
detecting unhandled HandledPromise rejections (in XS)

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#2344]
## What is the Problem Being Solved?

Unhandled promise rejections on XS are ignored (https://github.com/Moddable-OpenSource/moddable/issues/557 ) which makes them infeasible to debug. @michaelfig and I certainly had a tough time of it yesterday.

## Description of the Design

@erights had an idea on how to improve the situation at least for `HandlePromise`s

## Security Considerations

?

## Test Plan

Not sure, but one tiny test case is available:
https://github.com/Agoric/agoric-sdk/commit/8bc43261ff31fb2afd54fa043c836a1bf4c99fd3

**Comment by erights** [comment]
The existing Node unhandled promise rejection diagnostic doesn't work for us anyway because of the way we handle asynchrony. Because of this mismatch, Agoric effectively suppresses this diagnostic for much of our code anyway.

When this was first raised in tc39 ages ago. Several of us, including myself (and I think @kriskowal ?) suggested an alternate form of diagnostic. This bug is for me to prototype that in agoric-sdk first specifically for the HandledPromises of our eventual-send package. Once we've seen how well it seems to work, then we should revisit what deeper support we'd like from the platform.

**Comment by erights** [comment]
@dckc do you know what the status of this is?

**Comment by michaelfig** [comment]
> do you know what the status of this is?

I can vouch that we have adequate unhandled rejection diagnostics after `lockdown` in browsers and Node.js, as well as natively built into xsnap.  We can close this now.
