### ISSUE TITLE
create addVat() device

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#24]
Some Vats should have the ability to create new Vats. We should probably treat this authority as a "device", to provide it selectively to certain initial vats. This might also make it easier to provide certain authority over the new Vat: termination, migration, upgrade, and debugging.

**Comment by Chris-Hibbert** [comment]
Here are some more details on how the vat, kernel, and devices get tied together, and what functions rely on which others to get their work done. The main change from the previous description is that the vatAdmin Vat doesn't wait for a response from the device. It can construct the vat admin object immediately and return it with a promise for the root object.

The outer device has functions that allow the kernel to register createDynamicVat with the inner device.

The inner device remembers the mapping from adminID to vatID. It creates vats, terminates them, and can provide admin support. On creation, it only returns the new VatID to the vatAdminVat, and provides the root object in a follow-up reply. It has a function the kernel can use to notify it when vats have been created, but it doesn't have to register it, because the kernel will synthesize these calls. We expect a prompt reply to requests for statistics, so these will be returned immediately. Termination will be complicated

The vatAdminVat will be closely held and only provided to things like Zoe and the re-purposed contract host. It will have functionality for creating and adminstering (including termination) dynamic vats. When a new vat is requested, it will promptly return an admin interface and a promise for the root object. The root object promise will be resolved some time later, but messages can be sent to it immediately. The admin interface just wraps the vatID, and makes it possible to request info from the kernel and terminate the vat.

The kernel will have a method for creating new vats which will immediately return the new vat's ID. Once the new vat has been built, it will notify the vat creation device with a synthesized message passing the root object. The kernel will create the vat, then create the necessary entries in the kernel's tables so messages can be delivered.


Inner Device has
   calls registerVatCreationSetter(setVatCreationFunction) at startup

  * map from adminID to vatID
  * setVatCreationFunction(createVatFn)
     remembers the vatCreationFunction provided by the kernel
  * notifyNewDynamicVat(rootObject, adminId)
     called by the kernel.
     calls notifyVatCreated to pass the rootObject to the requestor 
  * create(adminId, code)
      return a vat ID
  * terminate(adminId)
  * getAdminInfo(adminId)
      return synchronously

Outer Device has
  * registerVatCreationFunction(fn)
        exported to kernel
        saves the kernel function that creates dynamic vats
  * registerVatCreationSetter
        exported to inner Vat
        Saves the inner vat's fn that sets the creation function

createVatFn is 
  * vatId? createVatFunction(srcString, adminId)

vatAdminVat
   map from adminId to root object
   nextAdminId

  * createDynamicVat(sourceCode)
    Called by vat code to create new vat
    calls D(device).create(nextId, code)
    return a management object and promise for the new vat's root object
       the root object won't respond until the vat is created, but that
        should be invisible to callers.

    The management object wraps the adminID and has:
      * getAdminInfo(details?)
          return synchronously
      * terminate()
          return synchronously
          may take a while to cauterize everything
          First step is to tell the dynamic vat to stop responding
          details to be worked out. May not be pretty initially.
  * notifyVatCreated(rootObject, adminId)
        called back by the device
        links the callable object to the new vat's root object


Kernel provides
  * createDynamicVat(adminId, sourceCode)
       registered with the device before other vats & devices
       returns the next vatID
       creates a new vat
       creates liveSlot entry for the new device' root object
       when the vat is ready, synthesizes a call to the device notifyNewDynamicVat(rootObject, adminId) 
  * getAdminInfo(adminId)
      synchronously returns info about the vat.

  Calls registerVatCreationFunction to invoke the function that remembers createDynamicVat
     After device has been initialized.

**Comment by Chris-Hibbert** [comment]
We implemented something slightly different, so here's a corrected reprise:

The outer device has functions that allow the kernel to register createDynamicVat with the inner device.

The inner device creates vats, terminates them, and can provide admin support. On creation, it only returns the new VatID to the vatAdminVat, and provides the root object in a follow-up reply.  We expect a prompt reply to requests for statistics, so these will be returned immediately. Termination will be complicated

The vatAdminVat will be closely held and only provided to things like Zoe and the re-purposed contract host. It will have functionality for creating and administering (including termination) dynamic vats. When a new vat is requested, it will promptly return an admin interface and a promise for the root object. The root object promise will be resolved some time later, but messages can be sent to it immediately. The admin interface just wraps the vatID, and makes it possible to request info from the kernel and terminate the vat.

The kernel will have a function for creating new vats which will immediately return the new vat's ID. This function will be registered with the device. Once a new vat has been built, the kernel will notify the vat creation vat with a synthesized message passing the root object. The kernel will create the vat, then create the necessary entries in the kernel's tables so messages can be delivered.

The inner device
 * calls registerVatCreationSetter(setVatCreationFunction) at startup
 * remembers functions provided by the kernel for creation, termination, and getting stats

The inner device has 
 * setVatManagementFunctions(createFn, terminateFn, adminFn)
 * create(adminId, code)   [return a vat ID]
 * terminate(adminId)
 * getAdminInfo(adminId) [return synchronously]
