### ISSUE TITLE
sendBroadcast in command-src.js can't handle BigInts

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#2559]
## Describe the bug

`sendBroadcast` can't handle BigInts

```
2021-03-02T23:22:22.642Z SwingSet: dev-command: error during sendBroadcast: (TypeError#1)
TypeError#1: Do not know how to serialize a BigInt
  at JSON.stringify (<anonymous>)
  at JSON.stringify (packages/tame-metering/src/tame.js:183:20)
  at Alleged: root.sendBroadcast (packages/SwingSet/src/devices/command-src.js:46:28)
  at meteredConstructor.invoke (packages/SwingSet/src/kernel/deviceSlots.js:208:26)
  at meteredConstructor.invoke (packages/SwingSet/src/kernel/deviceManager.js:80:36)
  at invoke (packages/SwingSet/src/kernel/kernelSyscall.js:78:28)
  at meteredConstructor.doKernelSyscall (packages/SwingSet/src/kernel/kernelSyscall.js:114:16)
  at vatSyscallHandler (packages/SwingSet/src/kernel/kernel.js:638:43)
  at doSyscall (packages/SwingSet/src/kernel/vatManager/syscall.js:78:18)
  at meteredConstructor.callNow (packages/SwingSet/src/kernel/vatManager/syscall.js:99:27)
```

## To Reproduce
1. Checkout `main` from https://github.com/Agoric/dapp-autoswap
2. In agoric-sdk, `yarn install` and `yarn build`
3. In dapp-autoswap, `agoric install`, then `agoric start --reset`
4. In dapp-autoswap but another terminal: `agoric deploy contract/deploy.js`
5. In dapp-autoswap: `agoric deploy api/deploy.js`
6. In dapp-autoswap: `cd ui` and `yarn start`
7. Approve the dapp in the wallet (`agoric open`)
8. Try swapping and look at the logs in the terminal where `agoric start --reset` is running. note that you have to chose the purses/brands first before entering values.

## Expected behavior
The method should be able to handle BigInts.

**Comment by warner** [comment]
hm, ok so the "command device" was previously specified to emit/accept JSON-parsable strings, and now we want more datatypes than JSON can handle, so we should enhance that to emit/accept marshal-stringify/parse-able strings, and exterior callers (e.g. HTTP handlers) must switch to using marshal instead of JSON.

I'll start with a change to `packages/SwingSet/src/devices/command-src.js` to replace the JSON calls with ones to `marshal`. But then we'll need to track down the places that use a command device and update them to match.

**Comment by warner** [comment]
It turns out that `command.js` (the external half of the command device) is the only code that observes the serialized strings coming out of `command-src.js`, and it immediately deserializes everything. So I can change that side to match, and the external API does not change (it just becomes capable of handling a wider range of datatypes).

Except:

* until #2018 is complete, it won't care for empty objects
* everything you pass through the command device, from both sides, must be `harden`ed first, which will require tracking down the code that uses the command device (both from the outside and within a vat) and adding `harden` calls

I'll leave this ticket open until we figure out those last two items.

**Comment by michaelfig** [comment]
Sorry to be a Davy Downer, but I'm not convinced that handling anything other than JSON is useful.  The command device is only used by `vat-http.js`, and that is only used by dapps who want to speak to their API server using JSON.

If the dapp UI is to interpret the packets correctly, it will need `@agoric/marshal` which needs SES, and the dapp UI will need to be able to accommodate the full range of what marshal can produce.  If we're bothering to use SES and send marshal-encoded data, why not just use `@agoric/captp` (which is already compatible with the command device because it explicitly uses marshal-over-JSON as its encoding)?

This is our chance to break from custom JSON-based protocols rather than trying to extend them.  The caveats to adding marshal support to the command device are unpalatable enough that I'd rather bypass it and finish the transition by ending up in captp.

**Comment by katelynsills** [comment]
> This is our chance to break from custom JSON-based protocols rather than trying to extend them. The caveats to adding marshal support to the command device are unpalatable enough that I'd rather bypass it and finish the transition by ending up in captp.

I agree with this. Let's figure out how to prioritize fixing them compared to the more fundamental changes in our software for Beta.

**Comment by katelynsills** [comment]
Here's [a related issue](https://github.com/Agoric/agoric-sdk/issues/2510) where the solution is to move dapps to CapTP. I've put it in my "Up Next" after refactoring amountMath as the prioritization coming from Dean. That would mean that we can not work on this issue, as moving to CapTP will solve it.

**Comment by warner** [comment]
We think everything is probably using captp by now, and if it isn't, it's broken and needs to be updated. So we can close this.
