### ISSUE TITLE
Enable better errors in AVA tests

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#2662]
## What is the Problem Being Solved?

We cannot currently see stack traces when Ava tests fail, which provides a bad user experience. ses-ava is an improvement, but we need to use it in Zoe and ERTP tests and provide it to contract developers.

## Description of the Design

Change `prepare-test-env` in Zoe to have:

```js
import { wrapTest } from '@agoric/ses-ava';
import '@agoric/install-ses';
import rawTest from 'ava';
```

**Comment by erights** [comment]
Until https://github.com/Agoric/agoric-sdk/issues/2663 is figured out, `prepare-test-env` should use exactly the import order @katelynsills shows above, even though it would make more sense to import `install-ses` first. As explained at https://github.com/Agoric/agoric-sdk/issues/2663, that won't work.

**Comment by erights** [comment]
More will be needed here than described above. The current users of `prepare-test-env` do not get their ava `test` function from importing `prepare-test-env`. Rather they import `ava` separately. To use ses-ava rather than ava, you need the three lines above plus a line making the ses-ava `test` function to use instead of the `ava` test function.


```js
import { wrapTest } from '@agoric/ses-ava';
import '@agoric/install-ses';
import rawTest from 'ava';

const test = wrapTest(rawTest);
```

But `prepare-test-env` is under src, not test. Having it import `ava` itself, so it can do this initialization will encounter the same problem our first attempt at ses-ava ran into. We don't want to promote `ava` from devDependencies to dependencies.

Attn @kriskowal @dckc @warner @michaelfig

**Comment by kriskowal** [comment]
This tidbit might not be useful, but presented for sake of completeness:

Moving ava from devDependencies to dependencies might be acceptable if ses-ava were a package that could only be consumed using -r esm, never to run on Node.js’s ESM module loader, never to be used as CommonJS.

This is generally true of packages in agoric/agoric-sdk, but not of packages in endojs/endo, but being so tightly coupled to -r esm is a liability long term.

**Comment by erights** [comment]
Could it make sense to instead move `prepare-test-env.js` from `src/` to `test/` ?

**Comment by michaelfig** [comment]
> Could it make sense to instead move `prepare-test-env.js` from `src/` to `test/` ?

Only if it is not used by other packages.

**Comment by erights** [comment]
Many other packages say

import '@agoric/zoe/tools/prepare-test-env'; 

So no. Thanks.

**Comment by dckc** [comment]
Is this a job for [peerDependencies](https://nodejs.org/es/blog/npm/peer-dependencies/)?

**Comment by erights** [comment]
ses-ava and its deployment in our code, both here and in select dapps, is in a reasonable state. I can finally close this!
