### ISSUE TITLE
how should validators choose to run vats on XS?

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#2676]
## What is the Problem Being Solved?

We currently use a `WORKER_TYPE=xs-worker` environment variable to test XS vats.

~~This is gross.~~ _Excuse me._ This is a risky use of ambient authority.

## Description of the Design

_something something genesis parameter something_?

_Feel free to re-assign back to me and/or @warner  when the design part is filled in._

## Security Considerations

?

## Test Plan

?

**Comment by dckc** [comment]
chatted with @warner ... he noted there are two kinds of swingset initialization options: ephemeral `runtimeOptions` like "do debugging _this_ time" and `initializationOptions` that go into the store and stick around when this swingset is restarted. This choice of vat manager type probably goes in `initializationOptions`... but in any case, it's important to **record the worker type when we put the source code and such of a vat into the store**.

That seems to be `vatKeeper.setSourceAndOptions`. I believe I see a few code paths that do **not** set `managerType` before calling that.

**Comment by dckc** [comment]
@warner have you figured out what design you prefer?

In #2676 I added a `--defaultManagerType` to `ag-solo`. But that's not straightforward to access from the `agoric` cli (used [Starting a Project](https://agoric.com/documentation/getting-started/start-a-project.html)) so I kept the `WORKER_TYPE` environment variable switch (though it moved to `initializeSwingset`)

```
WORKER_TYPE=xs-worker agoric start --reset
```

**Comment by warner** [comment]
Internally, we should make sure `managerType` gets recorded by `vatKeeper.setSourceAndOptions`. That already happens for static vats (https://github.com/Agoric/agoric-sdk/blob/29b6dee40379b32834630d2c5b852c9f124fb039/packages/SwingSet/src/kernel/initializeKernel.js#L75). For dynamic vats, if the caller provided a `managerType` it will get recorded (https://github.com/Agoric/agoric-sdk/blob/29b6dee40379b32834630d2c5b852c9f124fb039/packages/SwingSet/src/kernel/loadVat.js#L36), but most callers do not. We need to change that to supply a kernel-wide default if the caller did not override it, and record that value into the vatKeeper. The goal here is to make sure that once a vat is created, it uses the same managerType every time it gets reloaded in the future. Migrating vats from one managerType to another is just as consensus-threatening as migrating from one swingset to another, and will require nearly as much work.

(The issue is that JS is sufficiently underspecified that vat code can sense what kind of engine it runs on, which means it might behave differently on different engines, and we need to make sure that can't cause a consensus failure)

At middle level, we need a way to provide each swingset a default for that managerType. This default should be sticky: once a swingset is started with one default, every time the host application restarts, the new swingset instance should use the same one. That means the default wants to get saved to the `kernelKeeper` under some unique key. For this, `src/kernel/state/kernelKeeper.js` should change the `createStartingKernelState()` to `createStartingKernelState(defaultVatManager)`, and the function should store the value with `storage.set('kernel.defaultVatManager', defaultVatManager)`. The kernelKeeper should add a new function `getDefaultVatManager()` to retrieve it. The code in `initializeKernel.js` and `loadVat.js` which needs to know the default type should get it from `kernelKeeper.getDefaultVatManager()`.

At the next higher level, the host application which builds swingset needs a way to tell swingset what default to use. This ought to go into the `config` object, in a key named `defaultVatManager`, next to `.vats` and `.bootstrap`. The code in `src/initializeSwingset.js` needs to recognize and validate the new key, and pass it into `initializeKernel()`, which should pass it through to `createStartingKernelState()`.

At the level above that, our two host applications (ag-solo and cosmic-swingset) need to decide what value to provide. For cosmic-swingset, individual validator operators should *not* choose this, because the manager type is part of consensus, just like the set of static vats. All validators should be running with the same config, which defines both the static vats and the default manager type.

We need:

* 1: a way for us to flip the switch that validators will use when we decide to switch from Node to XS
* 2: a way for an ag-solo operator to choose which to use
* 3: a way for us to easily test that cosmic-swingset (in a testnet or local developer test) works with XS

For 1, I think cosmic-swingset should have a line of code whose value changes when we flip that switch, used to build the `config` object passed into `initializeSwingset`.

For 2, I think a `--vat-worker=xs` command-line argument on ag-solo would be fine.

For 3.. I'm not sure. I guess we could add `--vat-worker=xs` to cosmic-swingset too, and just document the fact that this is meant for testing and not for actual validators (maybe by not documenting it very loudly).

We could continue to honor an environment variable to achieve 3 in our CI runs without changing a lot of code. We might use that to control the default type in the integration-style tests like `cosmic-swingset` and the various dapp integration tests which run `agoric start`. It wouldn't affect the AVA `test/swingsetTests/` in Zoe and ERTP which don't use ag-solo/cosmic-swingset. For those, we'd need to change the `test-*.js` driver programs to recognize the environment variable and change what `config` they pass into `buildVatController`. If AVA has a way to provide additional arguments based on the AVA configuration, or maybe if `test.something` were populated with config data, we could do it without an environment variable, but I haven't investigated AVA enough to know if such a thing exists.

**Comment by dckc** [comment]
> Internally, we should make sure `managerType` gets recorded by `vatKeeper.setSourceAndOptions`. ...
> At middle level, we need a way to provide each swingset a default for that managerType. ...

I think I did those.

> At the next higher level, the host application which builds swingset needs a way to tell swingset what default to use. This ought to go into the `config` object, in a key named `defaultVatManager`, next to `.vats` and `.bootstrap`.

Working on this. I think I missed it earlier.

**Comment by dckc** [comment]
existing code has `defaultManagerType`; you suggest `defaultVatManager`, @warner ; surely these are two names for the same thing and they should be consistent, right? I'm following precedent and going with `defaultManagerType`; let me know if you'd like me to change everything to `defaultVatManager`.

**Comment by dckc** [comment]
> We need:
> 
> * 1: a way for us to flip the switch that validators will use when we decide to switch from Node to XS
> For 1, I think cosmic-swingset should have a line of code whose value changes when we flip that switch, used to build the `config` object passed into `initializeSwingset`.

Perhaps the `chain-config.json` file?

Failing that, the line that defaults to `'local'` in `initializeSwingset` could work.

> * 2: a way for an ag-solo operator to choose which to use
> For 2, I think a `--vat-worker=xs` command-line argument on ag-solo would be fine.

OK, I think that's working.

> * 3: a way for us to easily test that cosmic-swingset (in a testnet or local developer test) works with XS
> For 3.. I'm not sure. I guess we could add `--vat-worker=xs` to cosmic-swingset too, and just document the fact that this is meant for testing and not for actual validators (maybe by not documenting it very loudly).
> We could continue to honor an environment variable to achieve 3 in our CI runs without changing a lot of code.

My current strategy is to use `env.WORKER_TYPE` for both CI and for the semi-hidden `cosmic-swingset` option.

> Internally, ...
> At middle level, ...

This swingset level stuff is in one commit, with tests (currently: 9d5f03da4a78)
