### ISSUE TITLE
Separate cosmic-swingset part 1

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#2945]
## What is the Problem Being Solved?

`cosmic-swingset` was the first experimental monorepo we had for the Cosmos + SwingSet integration.  Since then, a new monorepo, `agoric-sdk` was created, and `cosmic-swingset` was absorbed into `agoric-sdk/packages/cosmic-swingset`.

However, the `packages/cosmic-swingset/lib/ag-solo` code should actually be broken out into a separate packages.

## Description of the Design

There will be more reorg later, but this factoring should help flatten the tree a little and make the following package interdependencies:

```
packages/solo: packages/cosmic-swingset packages/vats
packages/cosmic-swingset: packages/vats
```

Here is a proposed set of file location changes:

```sh
cd agoric-sdk/packages
# Remove leftover cruft.
git rm cosmic-swingset/lib/ag-solo/upload-contract.js
git rm cosmic-swingset/lib/ag-solo/vats/gci.js
# Create a package just for the solo-only files.
mkdir -p solo/src
git mv cosmic-swingset/lib/ag-solo/html solo/public
git mv cosmic-swingset/lib/ag-solo/vats/solo-config.json solo/
git mv cosmic-swingset/lib/ag-solo/vats/ui-agent.js solo/src/
git mv cosmic-swingset/lib/ag-solo/vats/vat-{host,http,uploads}.js solo/src/
git mv cosmic-swingset/lib/ag-solo/*.js solo/src/
git mv cosmic-swingset/lib/ag-solo/* solo/
# Create a package for the decentral services.
mkdir vats
git mv cosmic-swingset/lib/ag-solo/vats/chain-config.json -> vats/decentral-config.json
git mv cosmic-swingset/lib/ag-solo/vats -> vats/src
# Break any old references to `cosmic-swingset/lib`
git mv cosmic-swingset/lib cosmic-swingset/src
```

**Comment by michaelfig** [comment]
@warner this refactor is to help fix the most onerous coupling of `ag-solo` without biting off too huge of a PR.  Please propose changes to it as you see fit.

**Comment by michaelfig** [comment]
End state:
```
cosmic-swingset/src
solo/
solo/public
solo/src
vats/
vats/src
```

**Comment by warner** [comment]
That sounds like a decent starting point. The eventual target I'd like to aim for is closer to:

```
ag-solo: ag-local-vats, cosmos-chain-connector, swingset-solo
ag-chain: ag-chain-vats, cosmic-swingset
ag-chain-vats: zoe, etc
```

where "cosmic-swingset" knows how to run a swingset within a cosmos-sdk chain but doesn't have a vat payload. The dividing line isn't great, because many of the vats we'll run on the chain have specialized dependencies on devices or other go-side libraries, so we might put that split off until later when we understand it better.

We might make separate package for the simulated-chain + solo combination, which could depend on both chain-vats and local-vats.

swingset-solo is then on track to be a more generic vatrunner, something not agoric-specific at all (sort of where swingset-runner is now), but with a plugin mechanism for IO connections to various targets (including cosmos-chain-connector to talk to ag-chain).

But yeah, let's start with your plan, I like the idea of something bite-sized to start with.
