### ISSUE TITLE
AMM contract needs to give Wallet UI feedback for rejected offers

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#3056]
Background:
Current behavior: a user performs a trade on the AMM.  The resulting offer rejects due to failed offer safety - perhaps the AMM price moved too much in between.  The failure shows in logs but to the user the trade simply never resolves.  No indication is given of the failure.

The wallet needs to provide some indication of transaction success/failure to the user.  Perhaps a history of offers?

**Comment by erights** [comment]
See https://github.com/Agoric/agoric-sdk/issues/4360

**Comment by Tartuffo** [comment]
Possibly the work needs to be done in AMM and/or Zoe before the Wallet can know it failed.  Rejected vs. Satisfied offer.

**Comment by Tartuffo** [comment]
As discussed in Eng Sync today, we need to have the correct feedback to the user, to be implemented between the UI and the AMM contract (not a fundamental change to Zoe).

**Comment by erights** [comment]
> As discussed in Eng Sync today, we need to have the correct feedback to the user, to be implemented between the UI and the AMM contract ("not a fundamental change to Zoe").

The punch line is correct "not a fundamental change to Zoe", but the description can be misundertood ("between the UI and the AMM contract"). The problem is that the contract can lie about whether the offer's `want` is satisfied, so the UI should *not* rely on the offerResult from the contract to indicate this. The contents of offerResult are only according to the contract, and its meaning is specific to the individual contract. A dapp UI (including the AMM UI) can use offerResult to display info that is legitimately according to the contract. But whether a `want` is satisfied or not should be determined from the payouts.

We have talked about Zoe making this more convenient, such as by adding a method to UserSeat. The "not a fundamental change to Zoe" is that the wallet UI doesn't actually need Zoe to provide it more than it currently does, since the wallet UI has the proposal and the payouts.

**Comment by Chris-Hibbert** [comment]
We can add a function (`E(userSeat).wasWantSatisfied()`) to Zoe that would return a promise that will resolve when the seat has exited.
