### ISSUE TITLE
parameterize LMDB store to accept max DB size as a configuration option

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#3073]
Note: this task, originally titled "swingstore should grow LMDB when necessary" got redefined in discussion to be something somewhat different.  This opening comment is being retained for historical purposes, but please read the thread below to find out how the story ends.

## What is the Problem Being Solved?

`swing-store-lmdb` currently creates the LMDB with a `mapSize:` of 2GiB. From what we can tell, LMDB does a large `mmap()` of the backing file (with this size) for reads, and does normal filesystem `write()` calls for writes. The choice of `mapSize` effectively sets several things:

* the VmSize of the process, since it includes this large `mmap`ed region
* the maximum size of the database, since it cannot read data outside of the `mmap`ed region
* the apparent size of the `data.mdb` file (as reported by `ls`)
  * (the *actual* size under Linux and macOS starts out as nearly zero, because it is sparse, and only pages which are actually used will consume disk blocks)
* the actual size of `data.mdb` under WSL, because it doesn't seem to support sparse files

The phase3 ("staking dynamics") testnet died after 4 days because this 2GiB limit was reached (almost entirely because of transcripts). We plan to move transcripts out of the DB in #3065, however we'd still prefer that the swingset state be limited by disk space, and not an arbitrary 2GiB limit.

So the task is to grow the LMDB `mapSize` (using some `node-lmdb` API) as necessary.

## Description of the Design

We're thinking that every time the swingstore's `commit()` API is called, just after performing the commit, the swingstore should check the actual size of the DB, and if it is using more than half of the current maximum, double the maximum.

In the chain, we call `commit()` once per block, near the end (slightly before telling the cosmos-sdk database to commit). We know there are no pending LMDB transactions at this point, since the kernel has given up agency.

We must start from a large enough size to make sure the very first block won't overflow the initial `mapSize`. After that, we can tolerate blocks that use up to 100% of the old size. We'll need to do some experimentation to see what the initial size ought to be: clearly 2GiB is enough, but it might be nice to start smaller, maybe 32MiB or so. However the first block does a lot of work (bootstrapping everything), so it may store a non-trivial amount of state.

Starting smaller would also make unit tests easier to run on machines with less disk space (I think `mmap` fails if the disk isn't large enough to accomodate all the holes being filled in (and if it doesn't fail, it should), and it should speed up performance on WSL where it really does consume all that space).

To measure the currently-consumed space, we're hoping the LMDB `dbi.stat(txn)` API will return the right data. It has several return values denominated page counts, as well as one that reports the page size in use. We don't yet know how to interpret the results, but hopefully they can be used to compute the current usage. If not, we could fall back to an OS-level `stat('data.mdb')` call, and look at the blocks-used count (the same thing `/bin/du` does). However this probably won't work on WSL, and runs the risk of getting into a loop where we allocate 32MB, look at it and conclude that all 32MB is in use, double it to 64MB, look agains and see all 64MB in use, etc, doubling the filesize on each commit.

## Test Plan

The unit test should provide a mock LMDB object that reports fake sizes, and we then check that we call the change-`mapSize` API as expected.

**Comment by FUDCo** [comment]
In researching some of the particulars of how to do this, I find that the consensus of people in the LMDB world, notably the implementors, is that if you are trying to dynamically grow the `mapSize` value you are Probably Doing It Wrong. In their view, the size limit is intended as a safety backstop to keep a growing database from exhausting so much of a system's disk space that the host is left in a state where recovery is impeded.  Best practice seems to be to set the limit at whatever the maximum size is you're willing to let the database grow to.

Use cases for dynamically updating the limit value seem to revolve around shared hosting environments that have a bunch of different databases in use at once and you want to give something a quota that can be increased if needed.  When a database hits its size limit it throws a distinctive error that can be caught, at which point you close the db and then open it again with the new limit.  However, this will lose whatever transaction was in progress when the exception was thrown, which means it's really only a practical approach when you are in a position to retry transactions, which we aren't really (we're positioned to retry cranks but not blocks, and we use LMDB transactions for blocks).  There does not seem to be a graceful way to ascertain how big the db has gotten aside from a `stat` call on the `data.mdb` file, which is tricky because the reported value doesn't reflect how much space is actually in use but only what the high water mark is, so you can't just look at the size but instead have to monitor its growth over time, which does not sound like fun.

After having read a whole bunch on this, my recommendation is that we should not implement any kind of automatic growth strategy, but should just set the size much, much larger (they talk about sizes like 256Tb not being a problem).  Given that different hosts have different amounts of disk space that whoever is running them is willing to devote to running a swingset, it seems plausible that we might want to provide a way to set the size as a configuration parameter or command line flag.
