### ISSUE TITLE
cosmic-swingset should export LMDB max size option to validator config

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#3235]
## What is the Problem Being Solved?

Swingset relies upon the host application to provide a "HostStorage" instance in which to store all of the kernel state. Currently, any real application will use an instance of `swing-store-lmdb`. Each LMDB database is configured with a maximum size: this can be changed over time: the on-disk backing file will be grown to match the max size (however it is sparse, and doesn't actually consume this much space on most filesystems).

In #3073, we considered growing this max size whenever it appeared to be in danger of running out of space. For various reasons outlined in that ticket, we're not going to do that. Instead, `swing-store-lmdb` will accept an option to set the max size each time the DB is opened.

The task is to expose this option to the user, in this case the validator operator. We know that `cosmic-swingset` provides a handful of config files in which the validator operator can control the details of their node: some are consulted only at chain startup, some later, some must agree with all other validators, others are unique. Whichever one of these config files is both consulted at each process launch *and* is unique to the one node (not part of consensus) is the right place for this setting. `cosmic-swingset` should extract the max LMDB size from that config file and use it in the option bag passed to the `swing-store-lmdb` opener function.

Also, the validator documentation should mention this setting. A separate ticket will be filed about adding docs to the validators guide: operators need to watch the space used by the chain, make decisions about how much disk space they're willing to commit to their validator, and update the config file (plus reboot their node) as necessary.

You won't be able to start on this work until #3073 is complete and `swing-store-lmdb` accepts the new option.

cc @FUDCo

**Comment by Tartuffo** [comment]
Should we migrate entirely to SQL Lite?  That would eliminate the need for this.

**Comment by FUDCo** [comment]
> Should we migrate entirely to SQL Lite? That would eliminate the need for this.

This is something we're strongly considering, but it's a biggish task that's not something to do casually (and I'm prepared to bet that we _will_ do it as part of what's needed to implement stores with composite keys).  In contrast, adding the config option discussed here should be relatively trivial; it's just that the change needs to be orchestrated carefully since it potentially impacts the validators.

**Comment by FUDCo** [comment]
If this task is as it was originally posed, I think it should be on @michaelfig's plate.  If we redefine it as "use SQLite instead", then it needs to be retitled/rewritten as part of a longer conversation.

**Comment by michaelfig** [comment]
> If this task is as it was originally posed, I think it should be on @michaelfig's plate. If we redefine it as "use SQLite instead", then it needs to be retitled/rewritten as part of a longer conversation.

Okay, I reread the original issue.  I will gladly provide an option for this.

My main question is: if autogrow is not allowed, what value should we set initially?  If you have a beefier machine, I'd expect that the defaults should let you tolerate a bigger database.  Can we use some heuristic like 2x physical memory?  That seems better than a number-out-of-thin-air like 2GB.

I'm concerned that the LMDB size is effectively "under consensus", since if your node uses a smaller limit than the others, then it will die before all the other nodes.

**Comment by FUDCo** [comment]
Given the way LMDB works on systems that can do sparse files (which is, I think, all of them except older versions of WSL where this issue originally came up), there's no real penalty to setting the size arbitrarily huge -- say 100TB or more -- as the actual size will reflect actual usage and will grow dynamically as needed.  The max size in essence just caps how large the database can get.  In practical terms, this means that any max bigger than the size of the disk volume containing the database files means that the effective limit is the available space on the volume rather than what is configured.  Reasons for setting the max lower might be because you want to preserve some scratch space on the volume (for example, if the volume is shared with OS stuff like syslogs that might need space) or if you are doing a test whose resource consumption you want to bound or if you are running multiple swingsets at a time and want to control priority over space usage.  These kinds of things are unlikely in a production validator system, but having the control knob preserves flexibility.

With respect to consensus, I would expect that there will be a minimum disk space requirement that's part of the specs you need to satisfy to be a validator and that the value of this minimum might be adjusted upward from time to time as a governance action.  I could imagine setting the max to whatever this governance parameter is so that if validators run out of space they all run out at the same time (i.e., a sort of failure _by_ consensus as opposed to a failure _of_ consensus).

**Comment by Tartuffo** [comment]
I thought the issue here was that on Windows, it pre-allocates the file, and Windows does not support sparse files.

**Comment by FUDCo** [comment]
My understanding (confirmed by a quick G query) is the Windows _does_ support sparse files.  It was WSL's Linux-file-system-mapped-onto-Windows thing that didn't (though I understand this has been corrected in new versions).

**Comment by Tartuffo** [comment]
If so, I'm not the only one who was misled on this point when we discussed it!

Also, https://stackoverflow.com/questions/33508305/lmdb-maximum-size-of-the-database-for-windows

**Comment by Tartuffo** [comment]
We will require WSL 2.  We should just set the max LMDB size to a very large number (larger than disk size).  Allow some way to configure it.
