### ISSUE TITLE
Streamline Zoe Tests

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#3348]
## What is the Problem Being Solved?

Currently, Zoe tests are taking quite a long time. We don't know exactly why, but the recent GC changes may be related, along with the Zoe tests that specifically exhaust meters. The time reported for `yarn test` overall is on the order of 30 minutes. 

## Description of the Design

For Zoe specifically, we should identify and isolate the tests that are taking a long time. After that, we should create a separate test suite of quick checks of the important Zoe API checks. This quick-check test suite can be used for rapid iteration. The remaining Zoe tests can be triggered separately, after removing any long-running tests that are determined not be very helpful. 

## Security Considerations

We should ensure that our test coverage remains the same, unless we specifically decide otherwise.

**Comment by Chris-Hibbert** [comment]
The long poles in the zoe tests are `zoe-metering` and `brokenContracts`. With the switch to xs, the metering tests are largely unneeded.  I'm pretty sure the `brokenContract` tests are also testing conditions that no longer matter.  (After a quick glance, the only one that was obvious was a metering test.)

**Comment by warner** [comment]
A few swingset-specific things that might help:
* each time swingset starts, it uses `bundleSource` to create a handful of bundles that it will need (the biggest is the kernel bundle, but it also creates ones for vat-admin, vat-timer, vat-vattp, and two xsnap supervisor bundles)
  * these can take a couple of seconds
  * in many cases we've amortized the time to one bundling per test program, with a `test.before` that creates all the bundles once and passes them in as kernelOptions
  * test programs which run many swingsets can benefit from doing this, if they aren't already
  * unfortunately this means splitting work into multiple test programs gets less benefit
* AVA will run multiple test programs in parallel. I'm not sure if it runs multiple test *functions* within a single test program in parallel. If that's correct, splitting work into multiple test programs gets *more* benefit, counteracting the swingset bundling overhead
* I think we saw significant time spent injecting metering code during `bundleSource`. We should look into turning off that transform. First we need any swingset tests that want to exercise metering faults (infinite loops, mostly) to run the vat in question under `xsnap` rather than a local worker. I think this is default for our applications (`cosmic-swingset`, `ag-solo`), but test programs would need to set a `kernelOption` to switch to `xsnap` for the kernels run during tests.
  * This will also affect the runtime, because `xsnap` vats run at a different speed than `local` ones, but I don't know whether it's faster or slower.
* We recently added a `gc()` call to each crank, which surely slows things down. We could probably add a `kernelOption` to turn this off, since tests aren't running long enough for memory usage to be a problem. On the other hand, I'm very interested in learning about bugs in the GC code which might only be exposed by tests outside the SwingSet package.

**Comment by katelynsills** [comment]
Running `yarn test` in agoric-sdk/packages/zoe takes nearly 7 minutes currently:
```
date
Thu Jun 17 17:33:15 PDT 2021
time yarn test
...
  380 tests passed
  3 known failures
  9 tests skipped
  15 tests todo
✨  Done in 401.99s.
yarn test  1296.44s user 55.97s system 336% cpu 6:42.34 total
date
Thu Jun 17 17:40:09 PDT 2021
```

**Comment by katelynsills** [comment]
Removing `--verbose` and specifying a timeout of `10s` skips 17 tests but only takes one minute and a half:

```
Thu Jun 17 17:52:33 PDT 2021
  363 tests passed
  3 known failures
  9 tests skipped
  15 tests todo
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn test  454.29s user 44.31s system 580% cpu 1:25.90 total
date
Thu Jun 17 17:54:14 PDT 2021
```

Turning on --verbose prints the tests that timed out:

```
 ✖ Timed out while running tests

  7 tests were pending in test/swingsetTests/brokenContracts/test-crashingContract.js

  ◌ swingsetTests › brokenContracts › crashingContract › ZCF throwing on invitation exercise
  ◌ swingsetTests › brokenContracts › crashingContract › ZCF throwing in API call
  ◌ swingsetTests › brokenContracts › crashingContract › throw in makeContract call
  ◌ swingsetTests › brokenContracts › crashingContract › happy termination path
  ◌ swingsetTests › brokenContracts › crashingContract › happy termination with offers path
  ◌ swingsetTests › brokenContracts › crashingContract › happy termination refuses contact path
  ◌ swingsetTests › brokenContracts › crashingContract › sad termination path

  10 tests were pending in test/swingsetTests/zoe/test-zoe.js

  ◌ swingsetTests › zoe › zoe › zoe - automaticRefund - valid inputs
  ◌ swingsetTests › zoe › zoe › zoe - coveredCall - valid inputs
  ◌ swingsetTests › zoe › zoe › zoe - swapForOption - valid inputs
  ◌ swingsetTests › zoe › zoe › zoe - secondPriceAuction - valid inputs
  ◌ swingsetTests › zoe › zoe › zoe - atomicSwap - valid inputs
  ◌ swingsetTests › zoe › zoe › zoe - simpleExchange - valid inputs
  ◌ swingsetTests › zoe › zoe › zoe - simpleExchange - state Update
  ◌ swingsetTests › zoe › zoe › zoe - autoswap - valid inputs
  ◌ swingsetTests › zoe › zoe › zoe - sellTickets - valid inputs
  ◌ swingsetTests › zoe › zoe › zoe - otcDesk - valid inputs
  ```

**Comment by katelynsills** [comment]
With payments as remotables, not virtual objects:

```
katesills@kates-mbp zoe % date
Fri Jun 18 13:27:38 PDT 2021
katesills@kates-mbp zoe % time yarn test:unit
yarn run v1.22.5
$ ava test/unitTests/**/test-*.js -T 10s

Swap failed. Please make sure your offer has the same underlyingAssets and strikePrice as specified in the invitation details. The keywords should not matter.
  227 tests passed
  3 known failures
✨  Done in 32.97s.
yarn test:unit  156.06s user 19.88s system 527% cpu 33.337 total
katesills@kates-mbp zoe % date
Fri Jun 18 13:28:28 PDT 2021
```

**Comment by katelynsills** [comment]
`yarn test` from `agoric-sdk` root now takes:

```
yarn test  38.98s user 5.18s system 157% cpu 27.956 total
```

We went from 30 minutes to nearly 30 seconds! I think this issue can be closed.
