### ISSUE TITLE
Cannot send USDC to self: Error: value (a number) must be a Nat or an array

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#3367]
## To Reproduce

1. `agoric start --reset`
2. open the wallet; go to transfers
3. hit Send under USDC
4. enter 10; choose "to my own purse" and **USD Coin**
5. hit send
6. see alert: `Cannot send: Error: value (a number) must be a Nat or an array`

In the `agoric start` log, see:

```
2021-06-20T15:22:10.176Z SwingSet: ls: v10: Logging sent error stack (Error#7)
Error#7: value 10000000000000000000 must be a Nat or an array

  at assertLooksLikeValue (packages/ERTP/src/amountMath.js:134:16)
  at meteredConstructor.make (packages/ERTP/src/amountMath.js:198:11)
  at Alleged: purse.actions.send (packages/dapp-svelte-wallet/api/src/lib-wallet.js:278:58)
```

## Diagnosis

It looks like the problem is in `parseValue` in the ui...
https://github.com/Agoric/agoric-sdk/blob/1218ddde7a3c821fa4aa9f98be6f9c021f374934/packages/dapp-svelte-wallet/ui/src/display.js#L39

... which is called from `send`:
https://github.com/Agoric/agoric-sdk/blob/1218ddde7a3c821fa4aa9f98be6f9c021f374934/packages/dapp-svelte-wallet/ui/src/Transfer.svelte#L31

then in the API:
https://github.com/Agoric/agoric-sdk/blob/1218ddde7a3c821fa4aa9f98be6f9c021f374934/packages/dapp-svelte-wallet/api/src/lib-wallet.js#L278

In `lib-wallet.js`, if I add `@param {number} sendValue` I get a static error about the call to `AmountMath.make`.

## Platform Environment

verified on master @ c16fd6d

_I originally ran into this while on a branch for #2848 : 601ef07f2; I haven't verified that this happens on master, though all the problematic code seems to be on master._

cc @dtribble @Chris-Hibbert @katelynsills

**Comment by dckc** [comment]
verified on master at c16fd6db3

**Comment by michaelfig** [comment]
This code in `dapp-svelte-wallet/ui/src/display.js` was originally written to use BigInts, but was ported to just use numbers since ERTP didn't yet support BigInts.

The parsing/stringification can now use a library in `ui-components/src/display` to do these manipulations.  @katelynsills has the most expertise in using that library (having authored it), but changing the Svelte wallet is probably easier for me.  I will try to make this change in the wallet to fix the bug today.
