### ISSUE TITLE
agoric init --dapp-base always creates dapp-fungile-faucet

### ISSUE THREAD

**Issue by tgrecojs** [Agoric/agoric-sdk#3418]
## Describe the bug
`agoric init --dapp-base <repo-url> <project-name>` does not use the `<repo-url>` argument and instead always uses `dapp-fungible-faucet` as origin repo.

## To Reproduce
1. execute ` agoric init --dapp-base https://github.com/Agoric/dapp-treasury dapp-treasury`
2. view `agoric init` logs.

## Expected behavior
agoric cli should allow users to scaffold new projects using the template repo url specified in `agoric init`

## Platform Environment
 - OS: macOS catalina 10.15.7
 - node version : v14.17.1
 - is there anything special/unusual about your platform? N/a
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`): `@agoric/access-token@0.4.5-2-gf3e4f87d6`

## Additional context
Similiar issue used to exist with the `--dapp-template`  flag which resulted in me cloning sample dapp repos and then using the `agoric` command to install, run, etc. 

## Screenshots
https://user-images.githubusercontent.com/6646552/123495649-faba8480-d5fa-11eb-8489-cfc5cce77034.mp4

**Comment by katelynsills** [comment]
Hi @tgrecojs, thanks for reporting this. I think there is a confusion about `dapp-base` versus `dapp-template`. In order to specify a dapp template other than the default, you can use `--dapp-template`:

```js
agoric init --dapp-template dapp-treasury my-dapp-treasury`
```

In this example, `dapp-treasury` is being appended to the base, `git://github.com/Agoric/` to produce `git://github.com/Agoric/dapp-treasury` as the repo to clone the dapp from.

To change the base, you can use the `--dapp-base` option:

`agoric init --dapp-base git://github.com/tgrecojs/ --dapp-template dapp-treasury my-dapp-treasury`

which will clone `git://github.com/tgrecojs/dapp-treasury` if it exists.

We should probably update our documentation to clear up any potential misunderstandings. Let me know if you're up for this, but we could use an issue and a PR on our [documentation repo ](https://github.com/Agoric/documentation)to add some more explanation. 

Thanks again for reporting! It really helps us smooth out the experience for everyone else.
