### ISSUE TITLE
Productize Fred problem solution in governance

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#3514]

**Comment by katelynsills** [comment]
Here's a start: "Users who don't trust each other can rely on Zoe to enable them to interact with each other safely. There are limited things that Zoe can generically enforce, such as offer safety. These are very powerful, but are limited. For everything else, users must rely on the contract developer who writes the contract. However, a good contract developer will use Zoe to allow the user to prove important properties about the contract so that the user is not relying on the contract blindly. The particular important properties to prove are contract-specific, and thus, it is the responsibility of the contract developer to write their contract in such a way that they can be proved, and more so, provide functions that do the work for the user."
