### ISSUE TITLE
Metering test gives different results locally (for markm) vs under CI

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#3538]
See https://github.com/Agoric/agoric-sdk/pull/3537

**Comment by erights** [comment]
Hi @warner are you the best assignee?

**Comment by warner** [comment]
Since @kriskowal experienced something similar, I'm guessing this is a consequence of different versions of SES, which will cause different metering results. That one test (`test-dynamic-vat-metered.js` "meters decrement") is more sensitive to the precise value of the meter than I thought it'd be.

I have a plan to make it less sensitive. The current test works by creating a Meter with a capacity of 200k, then running a `consume()` function (measured as taking about 36500 computrons per execution) several times. The test puts a notification threshold at 100k, and expects the Meter to notify on the 3rd call, and expire/underflow on the 6th call.

The less-sensitive approach would:
* set the meter to 1M, set the notify threshold to 0, run consume() twice, to measure the usage on the first and second calls (from my experiment, the first call consumes about 1.5% more than subsequent ones). Assert that the notifier does not fire.
* create a new vat, with a new meter, whose capacity is set to FIRST+1.5*SECOND, and threshold at 1.5*SECOND
  * run `consume()` once, which ought to leave the meter at 1.5*SECOND: no notification, no underflow
  * run `consume()` a second time, which ought to leave the meter at 0.5*SECOND: notifier fires, no underflow
  * run `consume()` a third time, which should underflow

I initially had a test that simply reset the meter to a higher value (after measuring `consume()` once), but then I removed the "arbitrary reset" API (as well as the "increment" API) because those didn't seem like something that should be available in normal operation.
