### ISSUE TITLE
stat-logger dependency on canvas is a maintenance burden

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#3815]
## Description

stat-logger depends on canvas via vega, imported in `statGraph.js`.

This costs time for devs during `yarn build` and it seems to be a maintenance burden, as discussed in...
https://github.com/Agoric/agoric-sdk/pull/3814#discussion_r705888831

Perhaps `stat-logger` should move to its own repo? Maybe in the loadgen repo with the nightly perf stuff?

**Comment by michaelfig** [comment]
The main reason this is more of a burden than our other compiled dependencies is that it has both sources to compile (like the others), but (unlike the others) those sources aren't self-contained.

`node-canvas` compilation requires binary dependencies (`pango`, `cairo`) that need to be installed outside of the `yarn install` step.  We get lucky when `node-canvas` can download prebuilt binaries for our CPU, OS, and version of Node.js, but that doesn't happen unless its maintainers explicitly create them.

I'd be most in favour of having a separate `Agoric/stat-logger` Github repository so that this dependency is isolated from the SDK.
