### ISSUE TITLE
wrong Block.Header.AppHash

### ISSUE THREAD

**Issue by EmreNOP** [Agoric/agoric-sdk#3870]
Aug 26 07:44:02 agoric ag-chain-cosmos[29425]: Error: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected CAF9BBD1E47A80BF55C6A731B30A7838047F676CB36ED0488DBB54A72444B1D6, got 13C7BFCEB5AD1973054568C48196B85C53A8725A078338CAAFC863B717B3CD0F

faced this after the "ag-chain-cosmos unsafe-reset-all"  due to bad address problem. Node is not starting atm.

**Comment by dckc** [comment]
@EmreNOP would you please share your `.ag-chain-cosmos` directory with us?

use google drive or https://submit.agoric.app or something.

**Comment by EmreNOP** [comment]
https://www.dropbox.com/s/t3m344gcexp2rua/EmreNOP-ag-chain-cosmos.tar.bz2?dl=0
@dckc

**Comment by dckc** [comment]
thanks,  @EmreNOP !

for reference:

13.8 MB
md5sum: cce2197a6475b6754dc4dbd38e0bf690
sha1: f6a43c612c028e32c16254fb2718b02aaf107d07

`gs://slogfile-upload-5/dx-collect/34-wrong-apphash/EmreNOP-ag-chain-cosmos.tar.bz2`
https://storage.cloud.google.com/slogfile-upload-5/dx-collect/34-wrong-apphash/EmreNOP-ag-chain-cosmos.tar.bz2

**Comment by warner** [comment]
I spent the afternoon comparing those slogfiles against one of my monitor nodes. I haven't found anything conclusive so far. 

One curious issue is that the `allocate` meter diverged. This is the total memory allocated by the worker process (incremented by like 4MiB each time XS doesn't have enough free space to satisfy a slot or chunk request), and as far as we know, should not vary. XS was recently changed to use `mmap` to allocate memory, instead of `malloc`, and it's supposed to be storing the mmap size in the snapshot, so it ought to be stable across a snapshot/reload cycle.

But in vat `v5` (vat-mints), I saw the `allocate` number after delivery 11291 (crank 434260) go up (from 42074144 to 46268448) in testnet-monitor-4, but in EmreNOP's slogfile it remained the same. The number does go up in some later crank. I see similar divergences in `v10` (zoe) and `v1` (vat-bank).

We aren't using the `allocate` number yet, so it shouldn't be capable of causing a consensus failure, but it's still weird.

The deliveries and syscalls of EmreNOP's slogfile and testnet-monitor-4 are identical up to the point where EmreNOP's ends, during block 61029. It finishes crank 1557377 (to v10/zoe), and records the `deliver-results`, but does not record the `crank-finish`, and does not start the next crank. On the "correct" run (testnet-monitor-4), that block contains another hundred cranks.

If slog entries are being recorded correctly, this indicates either an interruption (SIGINT) during the last portion of the delivery loop, or an exception being raised in that same window. The `deliver-result` doesn't suggest any reason why the vat might be terminated, and a terminated vat should still emit a `crank-finish` slog event. The slog might be consistent with a kernel panic, and I don't have the stderr to tell.

(one task I'll put in the queue is to emit slog events upon vat termination and kernel panic, so we don't have to rely upon stderr)
