### ISSUE TITLE
Design: User seed phrase generation for backendless wallet

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#4008]

**Comment by dckc** [comment]
Some notes on relevant experience...

[RSign](https://github.com/rchain-community/RSign) is a browser extension wallet I developed in 2018. I intentionally avoided the user seed phrase ritual, since I didn't want anyone developing consumer-level expectations about the code. I just generated a private key and used a [tweetnacl](https://www.npmjs.com/package/tweetnacl) encrypted box to save it in browser localstorage.

More recently, in the context of refining our faucet, I did some work with cosmjs including `DirectSecp256k1HdWallet.fromMnemonic`.
https://github.com/Agoric/faucet/blob/35c4bb7234577df166cf6c08518b5f8c4e43115a/src/gift.js#L165

Also back in 2018, I re-implemented ethereum [Web3 Secret Storage](https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition) in order to understand how it works in detail.
https://github.com/rchain-community/rchain-api/blob/master/rclient/src/secretStorage.js

cc @michaelfig @warner @kriskowal

**Comment by dckc** [comment]
chatted with @michaelfig  .

notes in https://github.com/Agoric/agoric-sdk/issues/3995#issuecomment-963358207 are more clear

raw notes:

https://github.com/Agoric/faucet/blob/cosmjs-rpc/src/gift.js
https://cosmos.github.io/cosmjs/latest/proto-signing/classes/directsecp256k1hdwallet.DirectSecp256k1HdWallet.html#serializeWithEncryptionKey
https://wallet.agoric.app/web-solo/current/
https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker

**Comment by Tartuffo** [comment]
We have moved to Kepler for generating and storing these words.  This is adequate for now.
