### ISSUE TITLE
silence unnecessary logs

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#424]
It's important not to print logs that are redundant, especially when they happen frequently.

Otherwise, it is easy to chew up log storage on hosted platforms that charge for usage.

**Comment by DavidBruant** [comment]
I would add also that running ERTP tests locally was very log-noisy
In some occasions, it made finding failing tests and the cause hard

I don't know whether this is the same issue or whether i should open a different issue

**Comment by katelynsills** [comment]
@DavidBruant I believe most of the logs in the ERTP come from the `insist` function. Every time a deliberate error is thrown, it also gets logged.  I would support an issue about reducing logs if you'd like to make one. That's a good idea.

Finding failing tests should be relatively easy though, since we take the tape tests and pipe them through tap-spec so that the failing tests are printed at the end.
