### ISSUE TITLE
[agoric-cli] Connect Agoric-CLI to testnet?

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#501]
I think we want to connect the agoric-cli to the testnet. Currently it runs a version of scenario 3 cosmic-swingset locally, without the fake latency.

**Comment by michaelfig** [comment]
Currently, the testnet client either requires building from source using Golang, or running a Docker container.  I have in the past asserted to @warner that building from source is an advanced use case, since people need to clone agoric-sdk to do it.

So, I would be happy to add a "start the testnet client in Docker" mode to satisfy the novice case.  Note that this still needs to be manually provisioned (with a code from https://testnet.agoric.com).  We can improve all this as we go.

I also think that the fake latency mode should be the default.  That behaviour allows for least surprise when moving from development to the testnet.

**Comment by michaelfig** [comment]
Let's propose the cli command in this issue, to verify the user flow.

**Comment by michaelfig** [comment]
I suggest:

```sh
# Run the fake-latency scenario3
agoric start
# Synonym for the above
agoric start dev
# Run the testnet from the latest Docker image:
agoric start testnet
# Run from within the SDK (i.e. ensure Go artifacts are built and use them):
agoric --sdk start testnet 
```

Thoughts?

**Comment by michaelfig** [comment]
The general pattern for this proposal would be `agoric start [profile-name] [...profile-args]`

**Comment by katelynsills** [comment]
Those commands sound good to me!

**Comment by michaelfig** [comment]
> Those commands sound good to me!

Okay, the ball is in my court.  I hope to have a PR for review tomorrow morning.

**Comment by katelynsills** [comment]
> Okay, the ball is in my court. I hope to have a PR for review tomorrow morning.

Awesome!
