### ISSUE TITLE
[cosmic-swingset] SimpleExchange DEX UI

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#541]
Related to #440 (the backend task)

For Zoe Alpha, we need a DEX frontend. Our users will probably be familiar to something similar to 0x's frontend:

![68747470733a2f2f73332e65752d776573742d322e616d617a6f6e6177732e636f6d2f30782d77696b692d696d616765732f65726332302e706e67](https://user-images.githubusercontent.com/2441069/74573659-10636880-4f36-11ea-81ab-21c98e113409.png)

The user interactions will be similar that of autoswap where the exchange front-end (with the exchange backend) creates an offer which the user approves in the wallet. One difference is that unlike autoswap, offers to the exchange may hang around waiting to get a match (we're not going to build a cancel function in the UI for now). Because the exchange UI needs to display the users current orders, the exchange backend needs to have a mapping of the offers it sent to the wallet with the inviteHandle (aka offerHandle) that ended up being associated with that offer. The exchange backend should receive the inviteHandle from the wallet once the user accepts the offer and the invite is redeemed with Zoe. 

The simpleExchange contract will have a publicAPI with functions like Autoswap's `getPrice` function. The publicAPI will have:
* `getOrderBook()` which returns a JSON array of data about all orders
* `getOrder(inviteHandle)` which returns JSON data for a single order

^ (@Chris-Hibbert, @jfparadis Let's pin down this API so JF can have mock data). 

Diagramming of some of the flow: 

![2020-02-14-DEX-Wallet-interaction](https://user-images.githubusercontent.com/2441069/74573592-e316ba80-4f35-11ea-93d9-c2f2cd1e5ac8.jpg)

**Comment by katelynsills** [comment]
@jfparadis In the recent Zoe/ERTP meeting we thought this might be something you could help with. Let know if you want to discuss further or if it's not a good fit.

**Comment by jfparadis** [comment]
Sounds good. @katelynsills, would you have more docs about the requirements?

**Comment by katelynsills** [comment]
> would you have more docs about the requirements?

Want to schedule some time to go over the requirements together and then I can document them in this issue?

**Comment by katelynsills** [comment]
> showPayoutRules(inviteHandle) function.

could we call this `getOrder(inviteHandle)` to make it parallel to the `getOrderBook()` function?

**Comment by jfparadis** [comment]
@katelynsills, here is a first pass with mocked data:
https://github.com/Agoric/simple-exchange-frontend

![Screen Shot 2020-02-19 at 6 59 46 AM](https://user-images.githubusercontent.com/2583204/74846637-a7894100-52e5-11ea-9d19-d0b88d346007.png)

**Comment by Chris-Hibbert** [comment]
Very cool, @jfparadis! Do you need any more from the backend than `getOrderBook()` and `getOrder(inviteHandle)`?

**Comment by jfparadis** [comment]
@Chris-Hibbert, yes, a JSON mock of the return values would be great ATM.

I need to confirm a few items in addition to these:

1. In AutoSwap, the user is assays from specific. The exchange is therefore from his POV is made up-front not only to select a pair of, but also a pair of purses. In other words, the user is selecting upfront which current from which purse, and the approval in the wallet has nothing else match.

Do you want to keep this design for now? Do you want the offer to still contain the coded purses? 

I think this is correct, since the "buy" or "sell" is doing an actual withdraw from the purse at the moment of the buy/sell. 

2. Misssind ATM: the top nav selector of the currency pairs. 

Are the selections part of the contract? Is there a `getExchanges()` method to return them? I expect the return value be something that means, among other things, `<pair of assays>` (see below)

3. The **Wallet** panel on the page should display a filtered list of purses that contain one of the two assays for the exhange. Is there a `getPurses(<pair of assays>)` or do you expect the exchange gets all purses and does the filtering in-app? 

4. Is there a difference between "buy" and "sell" apart from the order of the assays?

5. Currently, pagination is working, client-side, for both "orderbook" and "orders". There is no no need to add `<offset>` and `<limit>` to the calls to `getOrderBook()` and `getOrder(<inviteHandle>)`.

6. As in (3) above, is there a `<pair of assays>`  parameter to `getOrderBook()` and `getOrder(<inviteHandle>)`, or do we have to do the filtering on the client side?

**Comment by katelynsills** [comment]
@jfparadis this looks fabulous!

**Comment by Chris-Hibbert** [comment]
I'm having trouble parsing this. I think your keyboard dropped several words. I'm gong to make some guesses.

> 1. In AutoSwap, the user <uses> assays from specific <??>. The exchange is therefore from his POV is made up-front not only to select a pair of <Assays>, but also a pair of purses. In other words, the user is selecting upfront which current from which purse, and the approval in the wallet has nothing else match.

I think you're asking about SimpleExchange, not AutoSwap.The AutoSwap UI allows the user to choose which good is the ask, and which is the offer. In the SimpleExchange, there will also be two pre-selected goods, and the user will be able to trade in either direction.

> Do you want the offer to still contain the coded purses?

Since the user might have more than one wallet containing a particular currency, I think we have 
to allow them to choose which one to pay from and be paid into.

> Are the selections part of the contract? Is there a getExchanges() method to return them? I expect the return value be something that means, among other things, <pair of assays> (see below)

I think this ought to work the same as autoSwap. I don't see how this was done in the previous API.

> 3. The Wallet panel on the page should display a filtered list of purses that contain one of the two assays for the exhange. Is there a getPurses(<pair of assays>) or do you expect the exchange gets all purses and does the filtering in-app?

I can add `getPurses()`. That would add another round-trip, wouldn't it? If the exchange doesn't have enough info to do the filtering locally (it only has presences and would have to ask for Assays from all the payments), then it might be cleaner in the Wallet.

> 4. Is there a difference between "buy" and "sell" apart from the order of the assays?

Nope.

> 6. As in (3) above, is there a <pair of assays> parameter to getOrderBook() and getOrder(<inviteHandle>), or do we have to do the filtering on the client side?

getOrder() shouldn't need it. If the handle is known to the exchange, it'll provide the info.
I think getOrderBook() doesn't need it because each SimpleExchange instance only handles a single pair of Assays. If the user wants to trade some other pair, they'll have to find a different exchange instance.

**Comment by jfparadis** [comment]
Thanks, apologies for the typos. I'm in brain-dump mode ;)

Overall:
- if the contract needs to encode the purses, then we are very close to what we introduced in AutoSwap.
- if each instance is a single pair of assays, we still need more calls to the server to get those assays.

Specific:
1. Yes, it works like AutoSwap: I mean that the contract is not only about assays and amounts, but also encodes which purses are involved. Like AutoSwap the user pre-selects the purses and the amounts when the contract is created.

This is very different from the exchange at 0x, and closer to AutoSwap, correct?

2. (I I still need confirmation, this is an important decision and difference from 0x, their top nav includes a `MarketsDropdown`) Is there a `getExchanges()` (or `getMarkets()`) that can be called in order to allow the user to select an exchange/market (top nav menu)?

> each SimpleExchange instance only handles a single pair of Assays

This indicates something different that I was not aware of, and in that case a `getExchange()` (singluar) is still need to obtain the metadata to display in various areas of the UI (should not be hard-coded in the client, to avoid client and server being out-of-sync).

In simple terms, if `getOrder()` and `getOrderBook()` return no item, how does the use know what a particular exchange instance is about?

3. Yes, the round-trip is necessary, but it's not to the same endpoint. We contact the wallet server, it can't come from the exchange server. Those can only meet in the client (no server-to-server communication), so the pair of assays need to be passed to the wallet.

The list of purses must be available to the client, like AutoSwap does it, otherwise there is no way to offer a selection to the user.

From a least authority POV, the exchange UI should access only the purses it needs for a given exchange.

Calls should be chained: `getExchange()` would return a pair or exchanges from the simple exchange back-end (again should not be hard-coded in the client, to avoid client and server being out-of-sync), while the `getPurses()` involves a call to the wallet to only return the purses applicable. 

Does that outweigh the concern of an extra round-trip?

4. Good.

5. n/c

6. Makes sense, but (2) is still required.

When can I expect a mock of the data?

**Comment by Chris-Hibbert** [comment]
> When can I expect a mock of the data?

Well, the json structure of an individual order is

```
[
  {
    "want":{"label":{"assay":{},"allegedName":"moola"},"extent":29},
    "offer":{"label":{"assay":{},"allegedName":"simoleans"},"extent":18}
  }
]
```

What format would be helpful? Do you want a function you can call from a test or a file with text in it, or what?

The assays in the fragment above are presences. The whole thing is embedded in `buys` and `sells` fields. So getBookOrders returns something like this:

```
{
  "buys": {
    [
	  {
        "want":{"label":{"assay":{},"allegedName":"moola"},"extent":29},
        "offer":{"label":{"assay":{},"allegedName":"simoleans"},"extent":18}
      },
	  {
        "want":{"label":{"assay":{},"allegedName":"moola"},"extent":15},
        "offer":{"label":{"assay":{},"allegedName":"simoleans"},"extent":7}
      }
    ]
  },
  "sells": {
    [
	  {
        "offer":{"label":{"assay":{},"allegedName":"moola"},"extent":92},
        "want":{"label":{"assay":{},"allegedName":"simoleans"},"extent":110}
      },
	  {
        "offer":{"label":{"assay":{},"allegedName":"moola"},"extent":38},
        "want":{"label":{"assay":{},"allegedName":"simoleans"},"extent":71}
      },
	  {
        "offer":{"label":{"assay":{},"allegedName":"moola"},"extent":41},
        "want":{"label":{"assay":{},"allegedName":"simoleans"},"extent":59}
      }
    ]
  },
}
```

**Comment by Chris-Hibbert** [comment]
How did we get the Assays from autoSwap? This doesn't seem like it should be different. Did I remove methods from publicAPI that we were relying on?  Was it available from `getPoolUnits()`?

> 1. Like AutoSwap the user pre-selects the purses and the amounts when the contract is created.

agreed.

> This is very different from the exchange at 0x, and closer to AutoSwap, correct?

Yes
> 2. (I I still need confirmation, this is an important decision and difference from 0x, their top nav includes a MarketsDropdown) Is there a getExchanges() (or getMarkets()) that can be called in order to allow the user to select an exchange/market (top nav menu)?

As you say, it's more like autoswap. This **simple**Exchange requires them to find the market they want somehow, and communicate that to the wallet. If that's not workable, we can add more calls.

> In simple terms, if getOrder() and getOrderBook() return no item, how does the use know what a particular exchange instance is about?

> Calls should be chained: getExchange() would return a pair or exchanges from the simple exchange back-end (again should not be hard-coded in the client, to avoid client and server being out-of-sync), while the getPurses() involves a call to the wallet to only return the purses applicable.

I get it now. I'll work on that when I can. I'm at Stanford the next two days, and in-between sessions may not give me enough time to focus. So EOD Monday is my target.

thanks for 'splaining it to me

**Comment by jfparadis** [comment]
@Chris-Hibbert FYI

In orderbook, the color is decided by order side:
```js
        const getColor = (order: OrderBookItem): string => {
            return order.side === OrderSide.Buy ? theme.componentsTheme.green : theme.componentsTheme.red;
        };
```
https://github.com/Agoric/agoric-sdk/pull/581

Same in order history:
```js
const SideTD = styled(CustomTD)<{ side: OrderSide }>`
    color: ${props =>
        props.side === OrderSide.Buy ? props.theme.componentsTheme.green : props.theme.componentsTheme.red};
`;
```

The 0x demo screenshot is incorrect.

**Comment by jfparadis** [comment]
@Chris-Hibbert, @katelynsills, if the JSON structure of an individual order is
```
[
  {
    "want":{"label":{"assay":{},"allegedName":"moola"},"extent":29},
    "offer":{"label":{"assay":{},"allegedName":"simoleans"},"extent":18}
  }
]
```
How can we differenciate it's a "sell" from a "buy"?

**Comment by katelynsills** [comment]
@michaelfig Do you think this can be closed?
