### ISSUE TITLE
[Zoe] Short-term splitting: Run ZCF + contracts in new vats

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#553]
Rough notes to be consolidated later: 

This is a "nice to have" for Zoe Alpha. 

This is not yet splitting out a "lower Zoe" which has different purses per contract.

There's a "upper" Zoe which is created per contract instance and put in the same vat as the contract. It has nearly all of the state.js tables and the contract facet. 

The "middle" Zoe is the long-lived Zoe identity that is exposed to the user as well as containing a constant identity for the inviteAssay. 

The Zoe Service API remains the same. Under the hood, `redeem` on the middle Zoe burns the invite and then calls the private upper Zoe for the specific contract with invite extent, offerRules, offerPayments.

The contract facet remains the same and is in upper Zoe.

Instance Table is split. The middle Zoe holds the mapping of instanceHandle to the private upper Zoe for that contract, which has an object with the data that was previously in instanceTable.

Core Requirement: Exhaustion of a contract's gas terminates only that contract

**Comment by Chris-Hibbert** [comment]
More detailed rough notes:

The plan is to move ZCF out of zoe.js into a separate source file. This code will be formatted as necessary for passing to createVat(). state.js will be split up. `IssuerTable` and `PayoutMap` will remain to be used by main Zoe (henceforth, just "Zoe"). 

`makeInstance()` will need access to the vatAdmin facet, and it will call `createVat()` to create a vat running zcf, and  start up a new instance from an existing installation. It will provide a private API. It will get back (a promise for) ZCF's private management API, which can provide the root invitation and instanceRecord currently returned by `makeInstance`. The installation will only manage the source code for the contract, and the evaluation will be done by zcf in the new vat.

I'll need to verify that all the cross-vat communication uses eventual sends.

The private API from main Zoe for ZCF includes `makeInvitation()`, which curries in the `instanceHandle`, but requires ZCF to turn the `offerHook` into an object with an `invoke()` method. ZCF will have a weakStore mapping `inviteHandle` to `offerHook`.

Contracts don't change much, since they mostly talk to ZCF, and that will still be in the same vat.

This task explicitly does not include separating out the purses for each instance. The purses managed by Zoe will continue to be managed centrally. This makes it possible to pay out if the contract fails for some reason. That also means we need to add handling for exit clauses in the main zoe.

Exit rules are already set up in offer (in main Zoe). The Timer for `afterDeadline` must be accessible to mainZoe, even if the Zoe contract facet is inaccessible. I think Zoe needs to validate that it trusts the timer.

When offer is called, Zoe deposits the funds, makes an offer result, and sends the amounts and invite extent to the contract, returning a promise for the result.  `{ offerHandle, payout, outcome, cancelObj }`

The `PayoutMap` is in Zoe, and `currentAllocations` are in ZCF (so ZCF can update them with local AmountMath operations). `currentAllocations` needs to be duplicated in Zoe, to support exit safety. I think every change to the `currentAllocation` should be streamed to Zoe, though it's plausible that the contract should be able to explicitly say "checkpoint now", and reallocations between checkpoints don't get committed to Zoe.

ZCF will repeat the relevant subset of the IssuerTable so it has the mapping from Issuer to Brand to AmountMath. (Which means it'll have its own issuersInProgress.) 

The current InstanceTable would be exploded. Zoe would have a mapping from instanceHandle to ZCF's management facet. ZCF (for each contract) would bind over the contract, and would know its `publicAPI`, `terms`, `IssuerKeywordRecord`, and `BrandKeywordRecord`. 

[See @erights' [HugeTable Survey](https://docs.google.com/document/d/1Q-LagINk2xAIpfg6DXVFk_ihbMRwPFpvWiPYAlBeTMo/edit)
