### ISSUE TITLE
Ergonomic issues related to handleExtent/Amount

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#559]
Related to my experience on #558 
(Also related to #521)

## The amount and extents are only useful for their identities

The only relevant tests that can be done is how many elements are in the amount array

https://github.com/Agoric/agoric-sdk/blob/4725143933e646efcbb1eda89068dcfbd811286c/packages/ERTP/test/unitTests/test-mintObj.js#L147

The extent (and consequently the amount) is not descriptive as it used to be. I understand that's by design. But maybe the amount could be descriptive with the addition of a `memo` or `description` field and additional optional parameter to `amountMath.make`

Not being able to add an extent/amount description led me to add the description in the payment. This led to another problem:

## Payment memo is a string

(depending on how the previous point is addressed, maybe this is irrelevant)

https://github.com/Agoric/agoric-sdk/blob/4725143933e646efcbb1eda89068dcfbd811286c/packages/ERTP/test/unitTests/test-mintObj.js#L117-L127
(see specifically line 126)
+ 

https://github.com/Agoric/agoric-sdk/blob/4725143933e646efcbb1eda89068dcfbd811286c/packages/ERTP/test/unitTests/test-mintObj.js#L146

I feel string is a bit restrictive
Here, a structured object is stringified and would need to be parsed again to get the structured object back
I think it'd be better if memo was a comparable. It would allow for structured objects to be used.

## There is no "handle" constructor

I have the intuition that `const handle = {}` is not beginner-friendly
It might make sense to provide a handle constructor even if it's only `function makeHandle(){ harden(Object.create(null)); }`. I feel `const handle = makeHandle()` will be more welcoming to beginners and in doc/tutorials

**Comment by katelynsills** [comment]
Copying over what I wrote in #558:

> I think there's two ways we could do the non-fungible example. One way (let's call it Version 1) is have the bare minimum identifier as the extent (perhaps using NatList). Then, there would have to be some API or offline resource to hit with that identifier Nat to learn what it is that you actually have.

> The other way (Version 2) is to put all of this necessary information in the extent. This is better because in Version 1, we are dependent on another entity to determine the meaning of our digital assets, and they might misbehave. But, it's also more verbose, so we might be needing a lot more on-chain storage which may become a key factor later on.

> It'd be great to have both of these options written out for Zoe Alpha, but I'm thinking that we might not have enough time for both. So, I think we should try Version 2 first. We will need to create a new MathHelpers that is based on the inviteMathHelpers, except without the instanceHandle. Perhaps we should drop the requirement to have an instanceHandle for inviteMathHelpers and use a renamed version inviteMathHelpers for both invites and these ballet tickets.

So we would want to keep the payment memo as a string. However, we probably want to come up with some other mechanisms to reduce its use as a store of asset information. Maybe it really only makes sense for fungible digital assets because in non-fungible cases, no two amounts should be the same, so there's no need for a memo?

I really like the handle constructor idea. Maybe that should be in `mathHelpers/utils`?

**Comment by erights** [comment]
To what degree does the old design, where the amount label also contained a `description` (typically a string) address this concern? To what degree does the pushback against the including `description` also bear on other solutions to this problem?

**Comment by erights** [comment]
Are you asking for a per-amount string or a per-`amountMath` string?

The `description` was per-`amountMath` and therefore intended to be per issuer. The `memo` cannot be in an amount at all. It is per-payment.

**Comment by erights** [comment]
Just talked to @katelynsills . I was indeed completely confused re what this issue is about. I thought it was about just using the brand identity with no description of that in the amount. It is actually about the need for more description within this specific extent, within the amount.

The memo field is not the right place because it is not inside an amount. The amount is our means of making requests through intermediaries. In particular, it is how you tell Zoe what you want. If you don't express it in the amount, Zoe cannot be sure to give it to you in exchange for taking your offer.

@katelynsills and I concluded we should probably just remove the `memo` field from payments. They are an attractive nuisance. This realization leads me to conclude that my old `description` string would have been as well. Good riddance.

**Comment by DavidBruant** [comment]
The state of the discussion is not clear to me. Here is the current conclusion i understand:
- `payment.memo()` goes away
- handle extents are not only property-less objects ([as they are planned now](https://github.com/Agoric/agoric-sdk/pull/523/files?file-filters%5B%5D=.js#diff-182bf53dd283832b3b6e9faeff3a9fd6R13)), but also carry the information describing the asset as properties

(an alternative to the second point would be:
- `amountMath.make` takes an optional argument describing the asset. This description is available on the amount object
)

**Comment by katelynsills** [comment]
Just following up here although we might have resolved this elsewhere. 

To confirm, `payment.memo()` is gone. 
Handles will continue to have no properties. 

We need to use the `setMathHelpers` for any data more complex than a string, such as in the opera ballet ticket case.

**Comment by katelynsills** [comment]
I'm going to close this, but this brought up a great discussion.
