### ISSUE TITLE
Possible simplifications of IssuerResults

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#597]
From the [current packages/ERTP/src/issuer.chainmail](https://github.com/Agoric/agoric-sdk/pull/523/files#diff-8acbd8944bccedc6f839cb5e7eccf6a5), `IssuerResults` looks like the following object:
```js
{
  mint: {
    getIssuer(), // same as issuer
    mintPayment()
  },
  issuer: {
    getAmountMath(), // same as amountMath
    getBrand(), // same as brand
    // ...
  }
  amountMath: {},
  brand: {}
}
```

- Given that `.amountMath` can easily be acquired from `.issuer`, i'm not sure it's useful to get it from `IssuerResults`
- Likewise for `.brand`
- More controversial, maybe `Mint` does not need the `getIssuer` since the issuer is now required to be "publicly" available in order for people with payments to make anything useful with them

**Comment by DavidBruant** [comment]
If everything is applied, `IssuerResults` could look like:
```js
{
  mintPayment(amount),
  issuer: {
    getAmountMath(), // same as amountMath
    getBrand(), // same as brand
    // ...
  }
}
```

**Comment by katelynsills** [comment]
I've found the return value of `produceIssuers` to be very helpful in usage. If you are minting, you often want the issuer immediately, and the amountMath immediately. I don't see a downside to having an additional way to obtain `issuer` and `amountMath` or `brand`, especially since you can just not mention them in a destructuring if you don't want them.
