### ISSUE TITLE
Use squash, disable simple merge

### ISSUE THREAD

**Issue by jfparadis** [Agoric/agoric-sdk#598]
Once a PR is approved, there are several options to bring the code from the feature branch to the `master` branch: the most important is whether squash is used or not.

The classic approach is to do a simple merge, without squash:
- All commits are preserved
- An extra "squashed" commit is added to the master branch.

This is the current view:

![Screen Shot 2020-02-25 at 8 59 38 AM](https://user-images.githubusercontent.com/2583204/75269624-11a25a00-57ae-11ea-9b63-31071d5e5c98.png)

Here are the pros:
- No squash preserve the individual commits made during the development of the feature branch

Here are the cons:
- It makes the history of `master` non linear
- The merged commit itself is a duplication of the individual commits
- Small individual commits are not always relevant

This non-linearity and duplication is visible in `git log`:

![Screen Shot 2020-02-25 at 8 58 07 AM](https://user-images.githubusercontent.com/2583204/75269982-a86f1680-57ae-11ea-8c6a-4043e13f5fae.png)

To obtain a linear view and remove the duplication, one can use `git log --first-parent master`:
![Screen Shot 2020-02-25 at 9 12 50 AM](https://user-images.githubusercontent.com/2583204/75270205-04d23600-57af-11ea-8d87-21968a74107a.png)

This view is much more useful, and it's exactly the same as if squash was used. 

Squash has these advantages:
- It prevents unnecessary merge commits from bloating the branch history (more concise)
- The history of the master branch is linear and more intelligible (no divergence)
- The squashed commit is exactly what was reviewed in the PR
- The history of master has exactly one commit per PR

Here is view of master branch of React, showing one commit per PR:

![Screen Shot 2020-02-25 at 9 29 01 AM](https://user-images.githubusercontent.com/2583204/75271660-672c3600-57b1-11ea-847d-7789bf87c551.png)

**Comment by dckc** [comment]
The biggest argument I've heard in favor of squashing PRs is that at every commit in the master branch, all the test pass and such; in particular, `git bisect` works.

I have never used `git bisect`, though.

I _much_ prefer to have all the intermediate history preserved, though. As you demonstrated with `git log --first-parent master`, the concise view is available to anyone who wants to see it.

Regarding the cons you cite:
> It makes the history of master non linear

I don't see how that's a con. It's an accurate record of what happened.

> The merged commit itself is a duplication of the individual commits

I don't see how it's a duplicate.

> Small individual commits are not always relevant

So squash those; perhaps as part of the PR review.

**Comment by katelynsills** [comment]
I'm a big fan of squash 👍

**Comment by warner** [comment]
This came up again today, when I noticed (and grumbled about) the width of our commit history getting a bit wide:

![tree](https://user-images.githubusercontent.com/27146/78927400-b07bd080-7a53-11ea-914d-864894e924e8.png)

I like the "two or more commits followed by a merge" pattern, as I think there are plenty of PRs that are easiest to follow when they're (conscientiously) decomposed into multiple commits. Smaller PRs, with only one commit, can be committed directly, without a merge. In this approach, the history is either linear (for small changes), or two-wide (for more complex PRs). Occasionally there will be a race between two PRs, and it might be three-wide or more, but hopefully this is rare:

![tree2](https://user-images.githubusercontent.com/27146/78928914-54667b80-7a56-11ea-9ae7-32678dd0965b.png)


We can make it more rare by trying to stay in the habit of rebasing our PR branches (and force-pushing them to the PR) shortly before landing, if `master` has moved on since we started that work. This also helps the PR's CI test the actual code that we're proposing to land, rather than something which doesn't incorporate what `master` has become after the branch was last pushed but before we finally merge it.

My main goal is to avoid the difficult-to-read history that results from a practice which either doesn't rebase ever, or uses merges from `master` *into* the feature branch. Twisted, which I dearly love, has a history that looks like this on a good day:

![twisted1](https://user-images.githubusercontent.com/27146/78927882-78c15880-7a54-11ea-9194-4c90f227afb6.png)

and this on a bad day:

![twisted2](https://user-images.githubusercontent.com/27146/78927902-81b22a00-7a54-11ea-8716-2d41ccff875e.png)

all of which is in the ancesty of current trunk, forever. (Twisted's choices are somewhat influenced by the branching model of `bzr`, where a pattern like this might not be such an issue, but I haven't yet seen git tooling to make it more readable)

So my current ask is to non-rigorously check trunk before we land a PR, and our branch is out of date, then rebase+repush and wait for the new CI run to complete. I don't especially want to force the issue, as some occasional overlap is no big deal, but I want to nudge us back towards a simpler history.

That said, @katelynsills and @michaelfig pointed out that it's better to either not care or to have automation to enforce the thing you care about, and I can't disagree with that. So I'll look into the github settings. @kriskowal found a "Require branches to be up to date before merging" setting that sounds right. I guessing that will disable the Merge button once `master` has moved forward, and you'd have to rebase and repush to re-enable it.

I'll leave open the top-level issue here, which is about enforcing a completely linear history, with one-commit-per-PR, by forcing a squash-merge for each PR. I'm not a fan of that (for complex PRs), but I'd like to leave the discussion open.. maybe somebody else feels more strongly about it.

**Comment by dckc** [comment]
> ... I noticed ... the width of our commit history getting a bit wide:

cool diagram. what produced it?

> I like the "two or more commits followed by a merge" pattern

concur

> We can [....] rebase our PR branches ... shortly before landing. This also helps the PR's CI test the actual code

yes, that's important

> ... it's better to either not care or to have automation to enforce the thing you care about

concur.

> @kriskowal found a "Require branches to be up to date before merging" setting

He's a good guy to have around :)

**Comment by warner** [comment]
And as an extra datapoint, https://github.com/Agoric/agoric-sdk/pull/902 just got filed to fix a broken trunk that escaped notice during the PR process because it overlapped with another change to the same source files. I first noticed the problem when a subsequent PR failed CI, and had to dig through the GitHub Actions pages to discover that actually `master` was broken before my changed code even got run.

**Comment by warner** [comment]
> cool diagram. what produced it?

It's `GitX`, on a Mac. It does a lot of git stuff, but I only use it for the visualization. The main downside is that it's been abandoned/picked-back-up/passed-around for a couple of years, so it's not really obvious to me who currently maintains it (if anybody) or where an "official" build/download is to be found. Homebrew has a copy that's probably good enough. There are a couple of annoying layout bugs but they're not too bad to work around.

On linux, `gitk` does something similar, as does the repository tab of VSCode and others. There's also an ascii-art mode of `git log` somewhere that approximates the same layout.

I update that visualization obsessively before and after each git operation, especially rebases and rewrites, to keep my mental model of the history and tree state aligned with reality.

**Comment by dckc** [comment]
Thanks. `gitk --all`, i.e. `!x-a` in emacs magit, is an ingrained habit of mine as well.

**Comment by erights** [comment]
@warner done, right? Closing.
