### ISSUE TITLE
Consider using forks for development

### ISSUE THREAD

**Issue by jfparadis** [Agoric/agoric-sdk#626]
The old "branches are for teams, forks are contributors" is misunderstood and this mean it's hard to use github to its full potential.

In reality though, we don't use branches for collaboration (multiple commits by different authors on a specific feature) and most branches are single-author.

**Naming.** This means that the naming of branches is all over the place. IAt the very least, if not using a fork, you should prefix your branch name with your user id: the current long list of branches is problematic, as people forget to clean. 

It makes it hard to evolve a branch strategy with different release versions and feature branches because those get lost in the mix. Allowing branch deletion rights means any one branch is at risk. 

Ideally, branches should be created in only 2 cases: releases branch and feature collaboration, and those should be locked. PRs from forks then can apply to master, releases, features. You can then lock down branch creation and deletion.

**Tagging.** Likewise, pushing on the master repo means all tags can be overwritten at any time, putting the tagging of releases at risk. 

**Security.** Forking is more secure for the reasons above but also because you can control the merges from forks more naturally. It's possible to do the same with branches, but that needs scripts, and those scripts need to be maintained and are key-person dependent.

**Comment by warner** [comment]
I'm up for using personal forks for development, and reserving `Agoric/agoric-sdk` for releases.

We've been pretty good about deleting finished branches, but one ongoing concern I have is how many branches are present when a new contributor forks our main repo: how can they tell what branches they should pay attention to? Depending upon when they happened to hit the "fork" button, they'd get some random snapshot of what was under development at that moment. Putting development branches in a separate fork would clean this up.

I mostly tried switching to this mode with Tahoe. The downside was that I had to have git "remotes" for each of my main coworkers, and to see what they were up to, I had to use something like `git remote update --prune` to fetch all remotes, instead of a single `git fetch`. GitHub has an online view (https://github.com/Agoric/agoric-sdk/network) that shows everybody's branches nicely, but to compute a diff or actually try someone's code, you need to add their fork as a remote and pull it down to your local machine.

@dtribble probably has some thoughts.

**Comment by turadg** [comment]
We often collaborate on branches in the repo
