### ISSUE TITLE
[Zoe] Do not wait on creation of payout payments before resolving payout promise

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#627]
```js
const payout = Promise.all(
        offer.units.map((units, j) => E(pursePs[j]).withdraw(units, 
```

should change to:

```js
 const payout = offer.amounts.map((amount, j) =>
        E(pursePs[j]).withdraw(amount, 'payout'),
```

**Comment by erights** [comment]
To explain this issue: The zoe user gets a promise for a payout, where a payout is an array for promises for payments. The user knows they are done exiting when this payout promise resolves. The issue is: what does it mean to be done exiting?

Previously, the payout promise was only fulfilled after zoe completed the offer *and* when all the withdraw requests that Zoe makes of potentially remote issuers, to withdraw payout amounts from pool purses, completes. But Zoe has no control of those remote issuers. Now, the payout promise fulfills when the Zoe exit is complete, including Zoe having sent off those `withdraw` requests and returning promises for them. Each of those promises in turn fulfills when the withdrawal completes, resulting in a payment.

**Comment by erights** [comment]
The previous design allowed one misbehaving issuer to block the user from receiving their payouts from other well-behaved issuers. The new version no longer has this vulnerability.
