### ISSUE TITLE
Flatten the monorepo, move nested packages to the same level

### ISSUE THREAD

**Issue by jfparadis** [Agoric/agoric-sdk#629]
Nested packaged are hard to manage/automate/understand a repository. In a monorepo, there is no reason to nest them, and they can be safely moved.

Here, the those nested packages are completely ignored by automation:

```
$ find . | grep package.json | grep -v node_modules
./package.json
./packages/simple-exchange-frontend/package.json
**./packages/agoric-cli/template/ui/package.json**
**./packages/agoric-cli/template/contract/package.json**
./packages/agoric-cli/template/package.json
**./packages/agoric-cli/template/api/package.json**
./packages/agoric-cli/package.json
./packages/zoe/package.json
./packages/swing-store-lmdb/package.json
./packages/default-evaluate-options/package.json
./packages/marshal/package.json
./packages/import-manager/package.json
./packages/wallet-frontend/package.json
./packages/registrar/package.json
./packages/weak-store/package.json
./packages/sharing-service/package.json
./packages/autoswap-frontend/package.json
./packages/acorn-eventual-send/package.json
./packages/same-structure/package.json
./packages/assert/package.json
./packages/spawner/package.json
./packages/tame-metering/package.json
./packages/ERTP/package.json
./packages/sparse-ints/package.json
./packages/transform-metering/package.json
./packages/captp/package.json
./packages/evaluate/package.json
./packages/swingset-runner/package.json
./packages/cosmic-swingset/package.json
./packages/transform-eventual-send/package.json
./packages/SwingSet/package.json
./packages/deployment/package.json
./packages/make-promise/package.json
./packages/bundle-source/package.json
./packages/pixel-demo/package.json
**./packages/eventual-send/integration-test/package.json**
./packages/eventual-send/package.json
./packages/swing-store-simple/package.json
./packages/store/package.json
```

**Comment by warner** [comment]
I don't know what to do about the template packages.. will leave that to someone else.

For the integration-test packages, @katelynsills would it make sense to have a single monorepo-wide integration test package? Or do you think we should continue to do separate integration tests for each individual package?

**Comment by katelynsills** [comment]
Sorry, I missed this question earlier. What I called 'integration-test' (let's rename it to "downstream package usage test") is testing whether the result of `npm pack`/`yarn pack` is usable downstream, using the package's own tests as they are currently. So we're testing whether a downstream packages has the same functionality as our tests, which is pretty cool. I suppose you could have a single test that tries to test all the packages, but that would be a different kind of test entirely, and not very extensive.

I think ideally, we would move the downstream package usage test code to a single Agoric repo (or package in a monorepo?). The code is currently pretty much duplicated in all the packages right now. It was duplicated because it was harder to figure out how to get Travis CI at the time to test code between multiple repos.

**Comment by erights** [comment]
@warner all our monorepos are flat, so closing. right?
