### ISSUE TITLE
`__dirname` not portable to xs (ambient no-no anyway)

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#66]
I rediscovered this while trying to reproduce my results on a mac:

```
# bootstrap with SES
.../SwingSet/test/test-controller.js (50) # Exception: bootstrap: get __dirname: undefined variable!
```

I kludged around it back on Sep 8, but it makes assumptions about the current directory that aren't portable between linux and mac:

https://github.com/dckc/SwingSet/blame/xs-platform/xs-platform/preload.js#L53-L54 ea55849e213b

**Comment by dckc** [comment]
@erights re authority around `import fs from ...`, my preferred approach is to use objects to represent file access, since using `fs.readFile()` to turn strings into file access is just like turning integers into pointers. I think the first time I saw the object-oriented IO technique was in Emily, but the (tamed) java File API works likewise, as does python pathlib.

My most recent attempt to implement the same file I/O API on node an xs is:

https://github.com/dckc/agoric-sdk/blob/xs-platform/packages/cosmic-swingset/lib/ag-solo/pathlib.js for node

https://github.com/dckc/agoric-sdk/blob/xs-platform/packages/cosmic-swingset/xs-platform/pathlib.js for xs

**Comment by erights** [comment]
For reference, the Emily paper is at https://www.hpl.hp.com/techreports/2006/HPL-2006-116.html
The E taming of the Java File API is at http://erights.org/javadoc/java/io/File.html

Hi @dckc, I like where this is going! A lot!

But I don't follow it in detail. The pathlib.js for Node exports 
```js
export default function makeNodePath(filename, { fs, path, temp }) {
```
whereas the pathlib.js for XS exports
```js
export function makePath(filename, { File, Iterator }) {
```
so I take it they are not intended to be replacements for each other by themselves. Instead, they are presumably to be called by platform specific initialization, so this is fine. I take it the objects they make should be replacements for each other, yes?

From the behavior of the methods, it seems the attenuation they grant is to access any file or directory that has the value of `filename` as a ***textual*** prefix? Besides all the normal problems of using text instead of structure, what about `".."`?

The methods of the two path objects are different in several accidental ways. However, the XS path object also has a `bundleSource` method, which seems like an odd layering.

With these issues cleared up, yes, I think this is exactly the approach we should take to provide an ocap API to a POSIX-style file system.

For Emily, Joe-E, E, Monte, and now WASI, it is important to provide an ocap API for POSIX concepts including POSIX-style file access. For SES, this is clearly important for Node. For browser, blockchain, and devices via XS, perhaps POSIX-style file system semantics should not be considered universal? Perhaps we must because we must universally talk about relative specifier strings in trees of named modules. That explains making some degree of reading universal, but writing?

**Comment by erights** [comment]
Of historical interest, see also 
http://www.combex.com/papers/darpa-review/security-review.html#taming
and
http://erights.org/elib/legacy/taming.html

**Comment by dckc** [comment]
> ... I take it they are not intended to be replacements for each other by themselves. Instead, they are presumably to be called by platform specific initialization, so this is fine.

yes.

> I take it the objects they make should be replacements for each other, yes?

in due course, yes. Development has been sort of lumpy, though; I would work on one platform for a while, then the other...
 
> From the behavior of the methods, it seems the attenuation they grant is to access any file or directory that has the value of `filename` as a _**textual**_ prefix? Besides all the normal problems of using text instead of structure, what about `".."`?

This API doesn't do anything about `'..'`. Nor about absolute paths nor symlinks. I haven't needed to so far. It could be added. Or layered on top.

> ... However, the XS path object also has a `bundleSource` method, which seems like an odd layering.

Yes... it would be tidier to layer that on top somehow, but it is in fact the least authority necessary in this context, based on Oct 30 chat with @warner (rough notes are above).

It would be nice if rollup would let us pass in file access, but I'm not aware that it works that way... though I did just run into the [precinct](https://www.npmjs.com/package/precinct) package, which does related work and has an option: " fileSystem: (default: undefined) set to an alternative fs implementation that will be used to read the file path.".

> ... Perhaps we must because we must universally talk about relative specifier strings in trees of named modules. That explains making some degree of reading universal, but writing?

Yes, lumping writing in was sloppy. There are parts of ag-solo that need to write kernel state or mailbox state or some such. But it need not be all mixed together.

**Comment by dckc** [comment]
According to the design in #2107 , we're not running the controller on XS , for now.

**Comment by dckc** [comment]
@warner the strategy as of #2573 is to endow tests with

 1. a `__dirname` set to where we found the test script and
 2. a version of `resolve` that has a list of fixups for when the `resolve` is used from a script that's not in the same directory.

Currently we need only 1 fixup.

Is this good enough?

https://github.com/Agoric/agoric-sdk/blob/master/packages/xsnap/src/avaXS.js#L130
https://github.com/Agoric/agoric-sdk/blob/master/packages/xsnap/src/ava-xs.js#L28
https://github.com/Agoric/agoric-sdk/blob/ccf2db44a7ce834d425c2fc4560d11c2ab1d7fb4/packages/xsnap/src/avaXS.js#L407

**Comment by warner** [comment]
This approach seems good enough for now, closing.
