### ISSUE TITLE
Registrar should only allow registration of well-known reliable services

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#69]
We had a bug in which an Assay created in a vat-mints hosted in a solo chain was registered with the shared registrar, causing some confusion. The ability to register public OCaps should probably only be accessible to code running on a public chain.

Developers will want to make contracts created with the contractHost or with Zoe accessible to others, but this should probably be done by asking Zoe or the ContractHost to register it, rather than making the registration facet widely available.

**Comment by katelynsills** [comment]
Hmm, good point. I don't think we want Zoe to have to know about the registrar at all though. Can the registrar know whether an object is part of its own machine vs another machine? I think this isn't currently possible, but could it be possible in the future?

**Comment by erights** [comment]
This issue makes clear that I don't understand what the registrar security model is supposed to be. Is it clearly stated somewhere?

**Comment by Chris-Hibbert** [comment]
I haven't seen it, or heard it articulated.

**Comment by michaelfig** [comment]
The error is that a remote object (hosted on an ag-solo instance) was published on-chain.  When the ag-solo instance was stopped, the messages queued for it just accumulate in the on-chain mailbox for that instance rather than breaking the connection with promise rejections like E and @agoric/captp would.

I don't think this is a failure of the on-chain services.  It's more like we just haven't decided if ag-solo connections are expected to come back up or if they are ephemeral.  Some kind of timeout for non-responsive on-chain mailboxes to reject their outward pointing clist entries might be desirable.  I'll leave it to @erights to describe the proper ocap/vattp mechanism.

**Comment by katelynsills** [comment]
Can we close this issue? There is good discussion here, but I think the task as stated is stale, since the registrar isn't be used and it may be desirable to have ag-solo objects published on-chain, even if the message won't always get through immediately.
