### ISSUE TITLE
[ERTP] ERTP Methods Should Accept Promises or Payments

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#711]
This is the outcome of a recent discussion with @erights:

Currently, our ERTP methods use `E.unwrap` (with two exceptions, which were simply overlooked) and accept either a payment or a promise for a payment, but _only if the promise was from the same vat as the issuer_, and the promise can be synchronously resolved to the payment. This means that many time, the user will have to do a `.then` or `await`.

This is a fragile API. However, it _does_ enforce the correct ordering of calls. For instance, a `withdraw` call from an external vat after a `deposit` call will always result in the withdrawal happening after the deposit. 

@erights proposed a different approach. We would return to using `Promise.resolve(paymentOrPromise).then` in our ERTP methods. This would allow users to use any promise that will eventually resolve to a payment, regardless of the vat of origin of the promise. This is much less fragile and easy to explain. 

However, it alone does not enforce the ordering that we need for `deposit` (if a vat makes a call to deposit and then a call to withdraw from the same purse, we want that same order (deposit and then withdrawal) to be the order that the calls are carried out in the purse vat). 

We will have two ways to deposit: `deposit` and `depositInOrder`. The large majority of the time, users will use `deposit`, which will only accept a payment. In the more advanced usage, we will have a second deposit method called `depositInOrder` that uses the `E.unwrap`, ensuring that the call is correctly ordered if it succeeds. Users of `depositInOrder` will only be able to use it with promises that originate from the same vat as the issuer. If, for instance, the promises come from the Zoe vat, `depositInOrder` will fail.

Concrete TODOs (updated as of March 18 2pm)
- [ ] Except for `deposit`, replace all usages of `E.unwrap(paymentP)` in ERTP with `Promise.resolve(paymentP).then(payment => `
- [ ] Change `deposit` to only accept actual payments and remove `E.unwrap` from `deposit`. Do not add `Promise.resolve(paymentP).then(payment => `  to `deposit`. This means that users would always need to do an extra `then`, losing pipelining, even if they had no ordering needs. However, this would execute in order.
- [ ] Add a new method `depositInOrder` which uses `E.unwrap()`. This is specifically for advanced users who will be able to understand which promises `depositInOrder` will accept and which it will not. This preserves both pipelining and order. `depositInOrder` and `deposit` should call the same helper method to do the shared functionality of depositing, despite their differences in the arguments that they accept. 
- [ ] throw an explicit error in `deposit` if the payment is a promise:

```
deposit(payment){
  if(isPromise(payment)){
    throw new TypeError(`deposit does not accept promises as first argument. Instead of passing the promise (deposit(paymentPromise)), consider unwrapping the promise first:
paymentPromise.then(actualPayment => deposit(actualPayment))`)
  }
  // actual deposit code
}
```

**Comment by erights** [comment]
As background, one of the great things about our current ERTP design is that a purse balance is the *only* mutable state that varies over time. All other state is either stable or makes a monotonic transition to "used up". That's why only `getCurrentBalance` uses the explicit "Current".

For presence arguments of remotely invoked methods, there are three choices
   * accept only the presence itself, forcing the user to do a `then` round trip, losing pipelining. This choice is consistent with processing the request when it arrives, preserving order.
   * accept a promise, do a `Promise.resolve(arg).then(...)`, and put the logic of the method in the success callback. This preserves pipelining and is easy to explain, but the method's actions are out of order. This requires a user that depends on order to do a `then` on the result, forcing a round trip and losing pipelining.
   * accept a promise, do an `E.unwrap`, and do the method's logic now. This preserves both pipelining and order, but it is almost impossible to explain how to use it correctly.

All the methods other than `deposit` thus have no delicate ordering need. `payments` are stable until they make a monotonic transition to used-up. All the issuer methods *other than deposit* that take payments are arguments should thus accept promises for payments and `then` them, weakening order that doesn't matter, preserving pipelining, and ease of explanation.

As Kate explains, we would explain the `depositInOrder` method as only for advanced users, the third option above. For the normal `deposit` method for normal users, there are two possibilities:
   * A `deposit` that does a `then` on its payment arguments, the second option above, unburdening the expression of deposits that don't need ordering without sacrificing pipelining, but needing to explain to users that "You must `then` on the result of the `deposit` before doing anything depending on the deposit."
   * A `deposit` that requires the argument to be an actual payment, not a promise, the first option above. This is equally easy to explain. We'd still need to explain the need for an extra `then` round trip. But now users would always need to do this extra `then`, losing pipelining, even if they had no ordering needs. However, this would execute in order.

It's not clear which of these two choices for normal `deposit` is better. @katelynsills and I went back and forth over this multiple times. We agreed that it depends what the normal patterns of non-expert use turn out to be.

In writing up this note, an additional reason for the second normal `deposit` choice above comes to mind:
   * The first `deposit` option above, when incorrectly omitting the `then` interlock, will often happen to work, leading people to accidentally shipping code that breaks under other schedules.
   * The second `deposit` option above, when incorrectly omitting the `then` interlock, will reliably fail.

It was this "seems to work" hazard that drove Dean and I to obsess about message order in the first place. I think I now favor the second normal-use `deposit` option.

**Comment by erights** [comment]
One moral of the story is that any method that uses `E.unwrap` on an argument (the third option above) is likely only for advanced users, as its use has a delicate requirement that is 
   * almost impossible to explain, 
   * that everyone, including the advanced users, will fail to use reliably.
   * that when used incorrectly will often happen to work, leaving these bugs undetected.

**Comment by katelynsills** [comment]
> [E.unwrap] that when used incorrectly will often happen to work, leaving these bugs undetected.

I thought that it was the opposite - E.unwrap will often fail, but will always fail instead of allowing the wrong order.

**Comment by erights** [comment]
It will always fail rather than allowing the wrong order. But the incoming message will often happen to carry a promise that synchronously resolves on reception, but might not under other schedules.

The example we talked through has this character. Say that Zoe, the invite redeemer, and the issuer are in three separate vats. The redeemer writes code like

```js
const { payoutP } = ...~.redeem(...);
const fooPayoutP = payoutP~.Foo;
payoutP.then(payouts => myFooPurse~.depositInOrder(fooPayoutP));
```

If the issuer and zoe happen to be in the same vat, this will always succeed. But if the issuer and zoe are in separate vats, this will sometimes fail and sometimes succeed. For the advanced users of `depositInOrder` this hazard is worth it. But it is a hazard we need to explain and that we all need to beware of.

**Comment by DavidBruant** [comment]
I've read everything. I feel out of my league on the topic of ordering
Feeling out of my league is not a problem in itself, but i wonder how much other people might feel lost on this topic as well
On one hand, i understand that the choice being made ("accept a promise, do a Promise.resolve(arg).then(...)") is made with the intention to do the "right thing" by default. This way, that people do not have to worry about ordering because ERTP will do the safe choice by default.
On the other hand, the introduction of another `depositInOrder` method will require to understand the difference between both so this difference can be documented

Is there a reference document on the topic of ordering?
If not, any visual graphics may help (even hand-drawn on paper or a whiteboard, even a bad quality photography)

semi-bikeshed: if `deposit` is the method that should be the default, maybe `depositInOrder` isn't a good name, because it suggests that `deposit` does its action "out of order" (whatever that means) which sounds negative and might nudge people towards `depositInOrder`

**Comment by Chris-Hibbert** [comment]
I'm not sure that a decision has been made about how to proceed. If there's no decision, it doesn't seem like it's time to switch the semantics, which must require re-verifying every use of `deposit()` that is followed by code that depends on its execution.

I couldn't parse this from the opening comment: 

> Users can either ensure that their withdraw call in the success callback to deposit (this is the easy-to-explain case), or in the more advanced usage, we will have a second deposit method called depositInOrder that uses the E.unwrap, ensuring that the call is correctly ordered if it succeeds.

There's an "either" here. The first possibility is that users need to ensure something about their `withdraw()` calls, but I'm not sure what. The second possibility is that "we" could add a `depositInOrder()` that uses `E.unwrap()`.

The first response describes three choices, but doesn't give them names. It then presents two possibilities for `deposit()`, and refers to the choices as "the second option above" and "the first option above". It then gives an additional pair of reasons for the second possibility in terms of "the first `deposit` option above" and "the second `deposit` option above". I really got lost there! I can either call them A and B, or "accept unresolved promises", and "require resolved presences".

My reading is that deposit() should not accept unresolved promises, and that `depositInOrder()`, while useful to advanced developers, is also dangerous, and we can predict that even advanced users will occasionally mis-use it.

Is there any work to be done?

**Comment by katelynsills** [comment]
@Chris-Hibbert I updated the original description with concrete TODOs based on all of the comments. @erights can you make sure that this matches your expectation?

**Comment by erights** [comment]
@katelynsills yes, that todo list is exactly right.

@Chris-Hibbert For all the methods other than `deposit`, I expect all async usage not to notice the difference, though it is possible. Golden log tests however might break because the test might produce a different correct internal sequence.

For `deposit`, the new for-expert-only `depositInOrder` preserves the current `deposit` semantics. By switching all of our uses of `deposit` to `depositInOrder` we minimize the chance that this change causes breakage. Once we are satisfied that things are still working, *then* we can start switching uses of `depositInOrder` back to `deposit` when it works, and not switch when it doesn't work.

**Comment by erights** [comment]
For the non-`deposit` methods, current synchronous (and therefore local) usage *will* break as part of this transition.

**Comment by DavidBruant** [comment]
> Change deposit to only accept actual payments and remove E.unwrap from deposit. Do not add Promise.resolve(paymentP).then(payment => to deposit. This means that users would always need to do an extra then, losing pipelining, even if they had no ordering needs. However, this would execute in order.

since deposit will be the only method to not accept promises (and throw on a promise i imagine), i anticipate people will try to use it with promises and might be confused by this method not working with promises. If there is an agreement on this anticipated problem, one solution could be to throw an explicit error:
```js
deposit(payment){
  if(isPromise(payment)){
    throw new TypeError(`deposit does not accept promises as first argument. Instead of passing the promise (deposit(paymentPromise)), consider unwrapping the promise first:
paymentPromise.then(actualPayment => deposit(actualPayment))`)
  }
  // actual deposit code
}
```

**Comment by erights** [comment]
@DavidBruant That's a good idea. We should do that.

**Comment by katelynsills** [comment]
@DavidBruant Seconded - great idea

**Comment by katelynsills** [comment]
I updated the above TODOs to include David's idea

**Comment by Chris-Hibbert** [comment]
Is there a function that will do the `isPromise()` check?

**Comment by Chris-Hibbert** [comment]
The answer I got on another channel was that 
```
  Promise.resolve(payment) === payment;
```

is the right way to test. I'm looking into getting makePromise to provide that, but I'll try to not let that block this PR.

**Comment by Chris-Hibbert** [comment]
` isLive()` and `getAmountOf()` didn't have unwrap, but I suspect they should do a `Promise.resolve(paymentP).then(payment =>` on their arguments. Am I correct?

```
    isLive: paymentLedger.has,
    getAmountOf: paymentLedger.get,
```

The other untouched methods (`getBrand, getAllegedName, getAmountMath, getMathHelpersName, and makeEmptyPurse` in issuers, and `payment.getAllegedBrand()` and `purse.withdraw()`) don't depend on the state of an argument.

I noticed these while updating the chainmail to annotate the semantic differences between various methods.

**Comment by katelynsills** [comment]
@Chris-Hibbert  yes that's correct, they should. This was missed and found by @DavidBruant

**Comment by katelynsills** [comment]
@Chris-Hibbert  added some more info to the description of how `depositInOrder` can only use promises that originate from the same vat as the issuer

**Comment by Chris-Hibbert** [comment]
Given issue 759, I'll have to retract the implementation of depositInOrder I have at this point, and inspect all calls to deposit (100+ of them) to ensure they're all sending presences.

**Comment by erights** [comment]
Expanding on the virtues of the second `deposit`. It helps make ordering hazards more visible in the code at the sending site.

Say at the sending site, before this change, we see code like

```js
...
... E(purseP).deposit(paymentP) ...
...
```

where `paymentP` is a promise. Even if this is a promise that `E.unwrap` would have worked on, it no longer matters. The user must pass a presence, forcing a round trip and losing the benefits of pipelining. Until the code is so changed, it will *reliably* fail. The fixed code would be something like

```js
...
... HandledPromise.resolve(paymentP).then(payment => E(purseP).deposit(payment)) ...
...
```

This makes it apparent at the sending site that the deposit will be requested later, so a stateful dependency on it is more apparent. The first `deposit` choice, the fully asynchronous one, does a similar delay with a similar reshuffling of order, but leaves to sign in the code at the sending site that there's an ordering hazard to worry about. So the second `deposit`, the presence-argument-demanding one, is thus less hazardous for both static and dynamic reasons.

@Chris-Hibbert and I noticed this additional benefit while talking through how this PR should proceed.
