### ISSUE TITLE
[Zoe] Facet Parameters

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#718]
Each call of `zoe.offer` has a set of names for the offer, matching set for the payments, and the matching names for the payout. Internal to Zoe, the allocations that are being reallocated are also using those names. 

We will need to change how Zoe deposits payments into purses and how Zoe reallocates to make these use brands rather than keywords.

@erights Feel free to edit this description

**Comment by Chris-Hibbert** [comment]
The goal of the Zoe Facets effort is to make it possible for contracts to not have to use a single set of keywords across all players/seats/offers. Each offer would continue to have keywords in its proposal that define the role each issuer is playing within the contract. Sometimes a contract would be instantiated with multiple keywords mapping to the same issuer (e.g. Fees being paid in the same currency as Bids). The contract only pays attention to the keywords, so it would be indifferent to this.

Many contracts would probably be less confusing if they use keywords consistently throughout, but Zoe shouldn't care how a contract wants to communicate with its clients. This means that Zoe would have to deal with offers, payments, payouts, deposits, and reallocation by brands associated with the offer's keywords rather than the contract instance's keywords. Zoe doesn't actually need to require consistent use of keywords across offers. If Zoe treated the keywords as specific to each offer, it could still enforce conservation and offer safety.

In order to support duplication of issuers within an instance, contracts would need to continue using keywords for reallocation, but the keywords could vary among offers. (This means that sparseKeywords could be dropped from `reallocate()`.) 

Since there aren't offer-wide keywords, issuers and amountMaths would be looked up by brand. Rather than specifying the mapping from keywords to issuers in `makeInstance()`, we could either require a list of issuers to be included in `makeInstance()`, or just require that all the issuers be known. Zoe would throw an error for unknown issuers in an offer. The contract would specify (via documentation) the required structure of terms, and how that would map to the structure of give and want for each possible invite. The invite's extents would repeat the terms, so those creating offers would know which issuers were required for each keyword in want and give of the proposal.

Zoe wouldn't cross-validate in `cleanProposal()`, so it may turn out that contracts have to include more checkhooks, (I'm not sure of this yet).

I think the first step  is loosening the coupling of the keywords zoe uses to store payouts and allocations to the global keywords. This happens in `offer()` and `reallocate()`. This includes the work described in #1021, where we should use the brands in the proposal to get the purses in which to deposit those payments. 

After that, in no particular order:

 * support contracts looking up issuers by brand
 * `doGetCurrentAllocation()` verifies that offer keywords are a subset of the instance keywords
 * `getAmountMaths()` should take brands rather than instance keywords
 * handle unknown issuers in `makeInstance()`
 * `completeOffers()` iterates through all the keys in `issuerKeywordRecord`, which would no longer work.
 *  add checkhooks if necessary to allow contracts to verify consistency btwn terms and proposal.

I expect to do all this work while evolving one of the contracts and its tests.


There will presumably be several more tasks I'll discover as I go, but I think this gives a good outline of where I'm heading, and how much work is involved.



I take no position on whether the benefits of this approach are worth the cost to make the change now. The current global consistency of keywords across a contract may be simpler in nearly all cases.

**Comment by katelynsills** [comment]
Closed by #1169, #116, #1129
