### ISSUE TITLE
[Zoe] Rename "roles"

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#719]
In #685, we should rename `rolesNames` (the keys of `roles`) to `keywords`, the values to `args` and the record which has `keywords` as keys and `args` as values should be called `argRecord`:

roles -> argRecord
rolesNames -> keywords
issuers/payments/payouts/amounts -> args

**Comment by katelynsills** [comment]
@warner can we get your opinion on how this connects to the concept of keyword in the Python world?

**Comment by warner** [comment]
If I'm reading it right, you're doing the moral equivalent of passing named/"keyword" arguments into the API functions. And/or you're doing something like Python's "named tuples", but with less low-level validation support. Both seem like a good idea, although you'll have to do extra validation to obtain the same sort of error-discovery properties that Python's equivalents provide.

Python keyword arguments are defined along with the function name:

```python
def foo(arg1, arg2, bar):
    code
```

Callers can do `foo(1,2,3)` or `foo(1,2,bar=3)` or `foo(bar=3,arg2=2,arg1=1)`, all with the same results. A caller who does `foo(1,2,nope=3)` or `foo(1,2,3,4)` will get a runtime exception. There are additional syntaxes to allow the recipient to collect all the remaining positional arguments into a tuple, and/or all the remaining keyword arguments into a dictionary (`def foo(arg1, *posargs, **kwargs)`), but that's not the default.

`NamedTuple` lets you define a constructor which knows its name and a list of named fields: `Point = namedtuple('Point', ['x, 'y'])`. Then you can construct instances with positional args like `point1 = Point(1, 2)` and/or keyword args like `point2 = Point(y=2, x=1)`. The fields can be indexed either like a tuple (`x = point1[0]`) or like an object (`x = point1.x`), the latter being the most interesting. Unlike regular objects or dictionaries, you'll get an error if you try to set additional properties (`point1.z = 3` throws an exception).

All those error-throwing behaviors are important for catching basic bugs, particularly typos, misspellings/misunderstandings of the API, and API changes over time. When fields are added or removed, call sites that have not been updated should probably throw an error rather than leaving some fields as `undefined`.

To do the same in Javascript, maybe there should be a validation function (probably factored out into a library) which looks at record for unexpected property names, and rejects it (with an explanation) if any are found, in addition to the usual checks that all the *expected* properties were present. (I'm guessing y'all already have this in place, but I just wanted to be clear).

**Comment by katelynsills** [comment]
Thanks so much, @warner. This is a great overview. We do have some validation functions, but we will be adding more validation and you're right that this should be probably be factored out into something more reusable, probably both for internal Zoe code and use by contracts.
