### ISSUE TITLE
[Zoe] Analyze denial of service attack potential in zoe.js when depositing payments

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#776]
@erights says: A misbehaving issuer might never ack or nack the deposit... at least either all or none of the deposits are requested.

We should consider how allowing promises for payments might affect this.

**Comment by katelynsills** [comment]
@erights, since deposit only accepts payments, not promises, and Zoe only accepts payments, can we close this issue or should we keep it open (with an updated description)?

**Comment by erights** [comment]
Open. I'll explain tomorrow.

**Comment by erights** [comment]
From a conversation on #853 . In that conversation I link to this issue, which I thought would create a backlink. But it doesn't. Editing a bit, there I say:


This has to do with the remaining payout liveness danger. Say that I place an offer with moola(20), bucks(5). Say that the bucks issuer is malicious and never makes progress, but the moola issuer is well behaved. Say that the exit condition is onDemand. Such an offer never gets placed because the payments are never escrowed. After I get impatient enough I cancel. I should get my moola refund payout.

Solving this is compat with our API (Hooray!). The key thing is to provide the offerResult record immediate, since that's where the cancelObj is found. Until cancelled, payout, outcome, and offerHandle all must remain unresolved promises, because the funds haven't yet been escrowed, the upcall hasn't been called, and there is no offer record to speak of.

**Comment by erights** [comment]
Closing as duplicate of #1271
