### ISSUE TITLE
[ERTP] insist fails to throw exceptions if you don't include the tagged template literal

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#78]
See: [pull request 522](https://github.com/Agoric/agoric-sdk/pull/522)

The template-based `insist` API can lead to silently ignoring an assertion. If the template literal is left off, no exception is thrown on a failed test. We will change the API to take the message as an optional argument; e.g.,
```
insist(sky.isBlue(), details`${sky.color} should be blue`);
```

The `details` helper will be available as a direct import and as `insist.details`. It returns an object that can print itself with the formatted message, or when `complain` is invoked, will report the real details to the console but include only the `typeof` information in the exception to prevent revealing secrets up the exception path.

Some simultaneous considerations:
- nodejs has an assert library, so our concern (from prior languages) about asserts not being run in production is largely address
- we want the operation to match the package name
- we want to minimize churn atm

so here's the plan
- [ ] name the base test `insist`
- [ ] use compatible signatures with the node `assert` module so we only need a rename later
- [ ] name the reporter `details`
- [ ] add a `toString` for the `details` so that it can be used with other exception mechanisms
- [ ] file a ticket for later to rename `insist` to `assert` and flesh out to match the node assert library

**Comment by katelynsills** [comment]
@dckc Github seems to be connecting your commits to this issue. Are they meant to be connected? I couldn't see the relationship immediately.

**Comment by dckc** [comment]
Probably I wrote #nnn in a commit message referring to a pre-monorepo issue. Then the repos got merged together and the reference got confused.

**Comment by katelynsills** [comment]
Ah, gotcha. Any way to undo it?

**Comment by michaelfig** [comment]
> Any way to undo it?

No. :frowning_face:

**Comment by katelynsills** [comment]
What about the nuclear option of filter branch? https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

Do the links disappear if the commit message changes?

**Comment by dckc** [comment]
I suppose there's a good chance that would work, but it doesn't seem cost-effective.

**Comment by erights** [comment]
In progress at https://github.com/Agoric/agoric-sdk/tree/78-better-insist-abstractions
Attn @katelynsills @dtribble

**Comment by dtribble** [comment]
...these details moved into the bug description at the top...

**Comment by dtribble** [comment]
Additional note from @erights wrt reporting:
The key thing is that the actual data values are reported only to the console. What gets rendered into the thrown error is only the `typeof` those data values and a hint to look at the console for the actual data. That way, the actual data values are available as diagnostic for debugging but not available to calling code that catches the errors.

**Comment by dckc** [comment]
poor-man's [sealed exceptions](https://monte.readthedocs.io/en/latest/semantics.html#exceptions) / [unsealException](https://monte.readthedocs.io/en/latest/runtime.html#__entrypoint_io__.unsealException)

**Comment by erights** [comment]
@dckc exactly!

**Comment by dtribble** [comment]
Some simultaneous considerations:
- nodejs has an assert library, so our concern (from prior languages) about asserts not being run in production is largely address
- we want the operation to match the package name
- we want to minimize churn atm

Original plan:  
- [ ] name the base test `insist`
- [ ] use compatible signatures with the node `assert` module so we only need a rename later
- [ ] name the reporter `details`
- [ ] add a `toString` for the `details` so that it can be used with other exception mechanisms
- [ ] file a ticket for later to rename `insist` to `assert` and flesh out to match the node assert library

New plan:  
- [x] make a new package called `assert` with API elements compatible with nodeJS APIs
- [x] name the reporter `details`
- [ ] add a `toString` for the `details` so that it can be used with other exception mechanisms
- [ ] incrementally convert packages to use `assert` rather than `insist`
- [ ] retire `insist` package
- [ ] rename methods using the "insist" naming convention to use an "assert" naming conventiom

**Comment by katelynsills** [comment]
Let's remove `insist` in the same PR in which we add `assert`. There's not any particular reason to keep `insist` around, as far as I can tell.
