### ISSUE TITLE
[Zoe] Rethink how users get `offerHandle`s

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#810]
I don't like how wonky this is, but the `offerHandle` can be gotten from the extent of the invite: 

```
const { extent: { handle }} = await inviteIssuer.getAmountOf(invite);
```

We need to do some thinking about how to make this as easy as possible for the user. I think returning the `offerHandle` with the invite is the wrong choice, though, because it prohibits promise pipelining. 

_Originally posted by @katelynsills in https://github.com/Agoric/agoric-sdk/issues/747#issuecomment-606238566_

**Comment by DavidBruant** [comment]
> I think returning the offerHandle with the invite is the wrong choice, though, because it prohibits promise pipelining.

I don't understand why it prohibits promise pipelining, but i'm very interested. Could you expand on that?

alternative solutions to getAmountOf:
- `issuer.getExtentOf(payment)`
- `zoe.getOfferFromInvite(invite)`
- allow the invite object wherever the offerHandle is accepted
    - If the offerHandle can be gotten from the invite's amount, this doesn't grant more auhority to people with invite and i think that it removes the need to think about offerHandles for all the simple cases where someone has an invite

**Comment by katelynsills** [comment]
Sure, if only the invite is returned, then the user does not have wait for it to resolve in all cases, whereas if a record is returned, the user must wait for the promise for the structure to resolve before using it. For instance:

```
const inviteP = zoe.redeem(....);
inviteIssuer.getAmountOf(inviteP);
```

Now that `deposit` doesn't accept promises this may not be as helpful. 

I'm uneasy about sending the invite back as an argument to Zoe. Something about that seems odd to me. It'd be good to have a design discussion on this specifically.

**Comment by erights** [comment]
What about a client side helper?
```js
const makeSomethingHelper = inviteIssuerP =>
  inviteP => E(inviteIssuerP).getAmountOf(inviteP).then(
      amount => amount.extent.handle);
```
returns a promise for an offer.

**Comment by Chris-Hibbert** [comment]
The link from invite extent to offerhandle is one step longer than depicted above, since there's also an array to be destructured:
```
   const {
      extent: [{ handle }],
    } = await inviteIssuer.getAmountOf(invite);
```

**Comment by erights** [comment]
Why destructure rather than index?

```js
const makeSomethingHelper = inviteIssuerP =>
  inviteP => E(inviteIssuerP).getAmountOf(inviteP).then(
      amount => amount.extent[0].handle);
```

Not longer. No heinous await.

**Comment by Chris-Hibbert** [comment]
So the usage would include a definition, perhaps in a helper file: 
```js
const makeGetInviteHandle = inviteIssuerP =>
  inviteP => E(inviteIssuerP).getAmountOf(inviteP).then(
      amount => amount.extent[0].handle);
```
We would call this once
```js
const getInviteHandle = makeGetInviteHandle(inviteIssuerP);
```
and then could use `getInviteHandle()` multiple times
```js
 const aliceInviteHandle = getInviteHandle(aliceInvite);
```

I certainly like this better than the destructuring assignment. Is there any reason not to include this in an include file somewhere?

**Comment by katelynsills** [comment]
That sounds good to me, but we should call it `offerHandle` and `getOfferHandle`.

**Comment by Chris-Hibbert** [comment]
I looked for a place to put this that would be accessible to everyone who needs it, and it took a while before the obvious (the second kind of obvious) answer arose. This should be a method on the inviteIssuer.

Any objections to my adding it there?

**Comment by katelynsills** [comment]
I think that would significantly change ERTP, right? Or do you mean an after the fact addition such that inviteIssuer returned from Zoe is not the original one? I think this needs discussion before we do anything

**Comment by Chris-Hibbert** [comment]
Yeah, you're right, it shouldn't be in ERTP.

Does it work to add it to zoeService? Other methods there take `offerHandles`.
It would already know the issuer, so the extra step of creating the `getOfferHandle` function wouldn't be necessary.

**Comment by erights** [comment]
How about just a locally importable client-side helper module?

**Comment by DavidBruant** [comment]
I'm realizing that there is a 1-to-1 relationship between invites and offerHandles and i think that this is in part a cause for the confusion between the two [including in terminlogy](https://github.com/Agoric/agoric-sdk/issues/805))

I'm going to share an analysis of where offerHandles are created, how they are used and how thing could be different in a way that solves the problem of this issue

---
Here is where offerHandles are currently created:

https://github.com/Agoric/agoric-sdk/blob/cf9346dde2a3fcea435af5149cb958aad5a8016d/packages/zoe/src/zoe.js#L107-L121

The offerHandle (named `inviteHandle` here) is used in 2 places:
- to be added in the extent
- to be used as key for `handleToSeat`

Inside `redeem`, this key is used to get the seat and make the redemption result:

https://github.com/Agoric/agoric-sdk/blob/cf9346dde2a3fcea435af5149cb958aad5a8016d/packages/zoe/src/zoe.js#L426-L430

--- 
**Proposal**

Interestingly, the usage of the offerHandle in `makeInvite` as a key for `handleToSeat` could be removed if the store was `inviteToSeat` instead
And i feel like that makes more sense conceptually as well to map the seat with the invite and not the offerHandle

As a consequence, i think that the offerHandle does not need to be created in `makeInvite`. And that makes sense conceptually too: an offerHandle is the key of an allocation in the context of a contract ("instance"). If the invite has not been redeemed, there is no reason to create an offerHandle, because there is no assets associated with the offerHandle yet

offerHandle does not need to be created in `makeInvite` and it could be created in `redeem` instead when it is needed for the purpose of creating an association between the offerHandle and assets

What flows from this change would be that offerHandle would be returned as result of `zoe.redeem()` alongside `seat` and `payout`. And that's how the user would get the offerHandle.

Because offerHandle is created in `redeem`, it cannot be in the invite extent and so it won't be there any longer

Now, the contract-side also needs access to the offerHandle (often to be used in seat methods). The current way it does it is via `zoe.makeInvite` before passing along the invite to the user.
I think this could be solved by adding a zoefc.getOfferHandle(invite) method
This method returns something only if the invite has been redeemed and that's good because the contract probably has no reason to manipulate an offerHandle before the invite has been redeemed (as it's currently possible)

**Comment by DavidBruant** [comment]
> adding a zoefc.getOfferHandle(invite) method

It's a bit tricker than i thought because invite is a payment that can be passed around

Because invite in a payment, there is a need for an inviteHandle that is distinct from the offerHandle

**Comment by DavidBruant** [comment]
> adding a zoefc.getOfferHandle(invite) method

adding a zoefc.getOfferHandle(**inviteHandle**) method
