### ISSUE TITLE
A one-method object is added to the redemption object when exit is onDemand

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#818]
https://github.com/Agoric/agoric-sdk/blob/7ceebe5f45333525eb59a9d6ec7a062f93ea2da7/packages/zoe/src/zoe.js#L444-L448

I feel this could be simplified into:
```js
redemptionResult.cancel = () => completeOffers(instanceHandle, harden([offerHandle])),
```

`.cancelObj.cancel()` feels a bit awkward

**Comment by katelynsills** [comment]
Yeah, agreed that `redemptionResult.cancel()` would be the best way to design this. However, our infrastructure below Zoe (@agoric/marshal) doesn't allow for this option. In marshal:

> // objects can only be passed in one of two/three forms:
// 1: pass-by-presence: all properties (own and inherited) are methods,
//    the object itself is of type object, not function
// 2: pass-by-copy: all string-named own properties are data, not methods
//    the object must inherit from Object.prototype or null
// 3: the empty object is pass-by-presence, for identity comparison

Because the redemption result is a record already with `seat` and `payout`, we can't have a method as well.

**Comment by katelynsills** [comment]
I'm going to close this, but we should probably document this design decision someplace so it doesn't always look so dumb :)

**Comment by erights** [comment]
> we should probably document this design decision someplace so it doesn't always look so dumb

https://github.com/Agoric/agoric-sdk/issues/804#issuecomment-607011373 refers to our new grand plan to change how presences are expressed, so that eventually (not soon) we can make function presences that can be remotely invoked with tildot. If we were first designing Zoe after this transition, `cancel` may very well have been such a function presence.

History dependent design is always painful, but is an inevitable price of success.

**Comment by erights** [comment]
> we should probably document this design decision someplace so it doesn't always look so dumb

https://github.com/Agoric/agoric-sdk/issues/804#issuecomment-607011373 refers to the new grand plan @michaelfig and I settled today, that would fix this. It introduces a better way to express presences, that solve a large number of problems. Eventually (not soon) we can make function presences that can be remotely invoked with tildot. If we were first designing Zoe after this transition, `cancel` may very well have been such a function presence.

History dependent design is always painful, but is an inevitable price of success.

**Comment by DavidBruant** [comment]
> However, our infrastructure below Zoe (@agoric/marshal) doesn't allow for this option.

Yeah, now i remember, we've already had this discussion and i had forgotten
Sorry about that
and thanks for the details
