### ISSUE TITLE
Consider making amountKeywordRecords argument of zoe.reallocate optional

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#829]
While working on the Zoe Opera ticket contract, i ended up using `zoe.reallocate` and i used this pattern:

https://github.com/Agoric/agoric-sdk/blob/8abed6b4489822ed3f324e84850cca55440db22b/packages/zoe/src/contracts/operaConcertTicket.js#L96-L102

The core of the idea is that various parties already expressed what they `want` in their `proposal`. I anticipate the most common scenario will be that a successful reallocation will end up allocating what they `want`, so one can leverage that information to create the `amountKeywordRecords`

I think this code could be integrated inside `reallocate` to be the default behavior when the second argument is not passed (and take the argument as it is passed when it is)

Related: it's been hard for me to figure out what's going on in `swap` for `amountKeywordRecords`

https://github.com/Agoric/agoric-sdk/blob/8abed6b4489822ed3f324e84850cca55440db22b/packages/zoe/src/contracts/helpers/zoeHelpers.js#L100-L104

... and to track down where `amounts` comes from and what purpose it's supposed to serve

https://github.com/Agoric/agoric-sdk/blob/8abed6b4489822ed3f324e84850cca55440db22b/packages/zoe/src/zoe.js#L406-L416

https://github.com/Agoric/agoric-sdk/blob/8abed6b4489822ed3f324e84850cca55440db22b/packages/zoe/src/zoe.js#L453-L454

https://github.com/Agoric/agoric-sdk/blob/8abed6b4489822ed3f324e84850cca55440db22b/packages/zoe/src/zoe.js#L390-L404

Even with the code, it's still not clear to me 

An offer manipulates lots of amounts: the GiveKeywordAmounts, the WantKeywordAmounts, the amounts related to payments. What are these amounts exactly in relation to the 3 amount categories? and why are these amounts to relevant one to perform a `swap`?

(maybe the swap concern is a different issue, but if a default value is chosen for `amountKeywordRecords`, then swap can choose to not pass the second argument and let `reallocate` do the work)

**Comment by katelynsills** [comment]
I think there's a major concept missing here. The `amounts` of an `offerRecord` are what will be turned into payout payments. It's the current allocation for an offer. So, `amounts` are initialized as the amounts of the payments escrowed (aka, the amounts in `give` with their keywords) with `empty` for the `want` keywords (#800 changes this slightly). 

I think you are recreating the `amounts` record (an amountKeywordRecord) in your function `completeAmountKeywordRecord` and that's why it seems hard to use `reallocate`. Reallocate is meant to be used after getting the current allocation `amounts` by doing something like:

`const { amounts } = zoe.getOffer(offerHandle);`

or `zoe.getOffers(offerHandles).map( ({ amounts}) => ...`

To reallocate, you have to alter these `amounts` and then pass them back to the `reallocate` function.

Trying to fix this, is it that it's not immediately apparent that  `amounts` is already an amountKeywordRecord? Would it help if it were named, 'amountKeywordRecord' or 'currentAllocation'? Or something else?

Swap takes the `amounts` associated with two offers and literally swaps them - now the second offer has the first's `amounts`. 

In your example, you are swapping a ticket for the money, right? So that the auditorium gets the money, and the user gets the tickets? Swap would be useful in this case, if the auditorium had an offer that escrowed a certain number of tickets, and that could be swapped with a user who escrowed the money for that specific number of tickets. Swap is not going to be useful if the offer for the auditorium has tickets allocated to it that should not be swapped. 

We will not be making the `amountKeywordRecords` argument of `zoe.reallocate` optional, so I am going to close this after a few days, but let's work together on figuring out the best way for the auditorium to mint tickets, perhaps on demand, so that the contract is simpler.

**Comment by DavidBruant** [comment]
> amounts are initialized as the amounts of the payments escrowed (aka, the amounts in give with their keywords)
> (...)
> To reallocate, you have to alter these amounts and then pass them back to the reallocate function.

I'm confused by this part

My train of thought is the following:
- My understanding of `reallocate` second argument is that it describes the expected post-reallocation state associated with each `offer`
- Each `offer` already has an expression of what each party wants from a reallocation via the `want` field
- As a consequence, I feel like a straightforward way to get the intended post-reallocation from an array of offerHandles is to map to the `want` fields

I'm confused as to why `amountKeywordRecords` would based `amounts` (which are themselves based on `give`) + "altering" them. I feel like this alteration leads exactly to recreating the `want`s


> I think you are recreating the amounts record (an amountKeywordRecord) in your function completeAmountKeywordRecord

I am not. The difference is that i use it on `want` fields and not `give` like `amounts` does

The part that `completeAmountKeywordRecord` shares with recreating the `amounts` record is complete `AmountKeywordRecord` for keywords which were blank. That's a very mechanical function (actually, it processing could be done inside `reallocate` too, but that's another topic)

but the resemblances stops here


> and that's why it seems hard to use reallocate

Using `reallocate` hasn't been hard
Actually, as soon as i realized that i could do
`amountKeywordRecords = offerHandles.map(o => zoe.getOffer(o).proposal.want)`, it made reallocate much simpler than i had understood so far

and that's the motivation for this issue. I feel like all usages of `.reallocate` based on `.amounts` (`give` under the hood) are more complicated than necessary... to the point where i feel even `.reallocate` itself can integrate some changes to simplify its usage

(sightly unrelated: i found the code of `reallocate` very elegant, well-commented and easy to read and understand)

> Would it help if it were named, 'amountKeywordRecord' or 'currentAllocation'?

Yes, i feel like `currentAllocation` could work or `currentAllocationAmounts` or `currentAllocationAmountsKeywordRecord`

**Comment by DavidBruant** [comment]
After discussion with @katelynsills i understand that the reallocation needs to adhere to constraints related to both `give` and `want` and there is no unique good default to know how a reallocation should happen. As a consequence, the `reallocate` function lets its user fully tell them from which offer what should be going where

This makes the issue not impossible, but a very complex constraint solving problem
I'm closing it
