### ISSUE TITLE
marshal cannot serialize standard Maps

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#838]
This came out in a discussion with @katelynsills about what the `getAvailableTickets` method could return in the Opera ticket contract

**Comment by erights** [comment]
For now, we can't serialize any kind of maps. For now though, given a map `m`, you can turn it into an array of [key, value] pairs by
```js
[...m]
```
which we can serialize. On the other side, given an array of [key, value] pairs `pairs`, you can turn it back into a map by
```js
new Map(pairs)
```

Longer term, in the https://github.com/Agoric/agoric-sdk/tree/passable-collections branch I'm working on passable collections which can be marshalled and unmarshalled correctly, and whose key-lookup-equality is `sameStructure` equality, which is the equality preserved by our marshal and distributed object semantics. But this won't happen soon.

**Comment by erights** [comment]
The need for passable collections is already described or started in other issues and PRs. The so-called "passable collections" would include passable sets and passable maps. However, that's as far as this support should go. Marshal should *not* serialize standard sets and maps. Since the others remain open I'm closing this.
