### ISSUE TITLE
Please provide a helper to replace `zoeNotify`

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#841]
The following `zoeNotify` "helper" currently in [dapp-simple-exchange](https://github.com/Agoric/dapp-simple-exchange/blob/master/contract/zoeNotifier.js) has an interface I mostly like (except for its dependency on `timerService`):

```js
const { setHandleState, firstP: firstNotifyP } = zoeNotifier({
    zoe,
    timerService,
  });
```

And then you call it when you want to update a string indicating the "state" of a given `inviteHandle`:

```js
      if (canTradeWith(inviteHandle, iHandle)) {
        setHandleState(inviteHandle, 'matched');
        setHandleState(iHandle, 'fulfilled');
        bookOrdersChanged();
        return swap(inviteHandle, iHandle);
      }
```

The point is that `firstP` resolves to `{ [state]: [...inviteHandlesMatchingState], nextP }`, where `state` is user-supplied (in the call to `setHandleState(inviteHandle, state)`, or `"inactive"` which is automatically detected (via polling the `timerService`).

What I'd *really* like is for `state = "inactive"` and `state = "active"` to be automatically managed by Zoe via the helper, and have the helper only need `zoe` as a parameter.  This will require Zoe to somehow notify the helper when `"active"` and `"inactive"` changes for this contract.

Even better API would be something like:

```js
function makeInviteHandleNotifier() {
  // initialize notifications, then...
  return { setHandleState, firstP }; // name bikeshedding appreciated
}
```

Design discussion would be useful here.  I have no opinion on how it should be done, just that something like `makeInviteHandleNotifier` should be added to the `makeZoeHelpers` return result.  Keeping track of handles and notifying their clients of changes is something that many contracts will want to do.

**Comment by Chris-Hibbert** [comment]
I want to maintain the promise updating chain in this design. The details of how the updates should be chained were described in issue #253. 

There are two kinds of state being tracked here: whether the offer is still active, and the state of the offer with respect to the contract. 

Only Zoe knows when the active offers change, but these changes are isolated in the offerTable in state.js. If we add a promise-update pipeline per offer, we can make it possible for anyone with the offerHandle to ask for the stream of updates. 

The contract knows when the contract state for each offer changes, and updates offers when the appropriate action happens. Different contracts, and often different seats in a contract should have separate streams of updates about their state. 

The contract could combine the updates from the offer's update stream and changes due to contract state into a single stream of events. It might also make sense to have them as two separate streams. I think this is a lesser alternative.  The current wallet handles a single stream, but it's not clear if that because that's the best for its use, or because that's what was easiest to support with the timer-based solution.

I the absence of others weighing in, I think I'd go with a structured record in the promise resolution with parts for zoe's state of the offer, and the contract's state. I'd have a promise stream per offerHandle, since that's the division of control for the handles.

Opinions?

**Comment by katelynsills** [comment]
I think this is in line with what you are saying, but just to be concrete, we would add a new property `changed` which is a promise, in the offerRecord in state.js, and then when the offerRecord is updated (usually, just the amounts are changeable), the promise is resolved? If the offer is completed, the offerRecord currently is deleted, so I think we cannot capture that change here without redesign.

**Comment by Chris-Hibbert** [comment]
It ought to be sufficient to send an update on completion notifying that it has reached a final state, and then not providing a next promise as it usually would.

**Comment by michaelfig** [comment]
The only time I actually need help from Zoe is to detect if somebody has invoked their offer's exitObj.  If you can provide just that primitive, I think the contract has everything else it needs to be able to implement a contract-level (not Zoe-level) library that can accurately track both Zoe and contract states for the offerHandles.

**Comment by katelynsills** [comment]
> It ought to be sufficient to send an update on completion notifying that it has reached a final state, and then not providing a next promise as it usually would.

I like this a lot, and @michaelfig this will cover your cancellation case nicely.

**Comment by dtribble** [comment]
As with the Offer Keywords, should we require that the state names start with an uppercase letter?

**Comment by katelynsills** [comment]
I think if the table property names are not user provided (which they shouldn't be) we don't need them to start with an uppercase letter. I tried to uppercase the exit conditions, but Mark pointed out I shouldn't, since it's not user-defined.

**Comment by Chris-Hibbert** [comment]
> The only time I actually need help from Zoe is to detect if somebody has invoked their offer's exitObj. 

It took me some research to figure out you meant the `cancelObj` that is returned when `exitKind === 'onDemand'`.  (mentioning here for  others' benefit.) We can include a status change for that.

> If you can provide just that primitive, I think the contract has everything else it needs to be able to implement a contract-level (not Zoe-level) library that can accurately track both Zoe and contract states for the offerHandles.

The way it does it now is by calling `zoe.getOfferStatuses(activeHandles)`. If we build the promise updating mechanism, Zoe can provide that information exactly when a change has happened, rather than requiring clients to poll for updates.

**Comment by katelynsills** [comment]
> It took me some research to figure out you meant the cancelObj that is returned when exitKind === 'onDemand'. (mentioning here for others' benefit.) We can include a status change for that.

@Chris-Hibbert calling `cancel` immediately calls `complete`, so this is the same case that you and I were talking about above - how to notify when an offer is completed.

**Comment by katelynsills** [comment]
I'm removing all assignees but @Chris-Hibbert  for clarity. Anyone who needs to review can be added as an assignee to specific PRs, not this issue.
