### ISSUE TITLE
[Zoe] Rename `offerRecord.amounts` to `offerRecord.currentAllocation`

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#847]
It was not previously clear what `offerRecord.amounts` was. 

See https://github.com/Agoric/agoric-sdk/issues/839 and https://github.com/Agoric/agoric-sdk/issues/829 for some discussion on what they might mean. 

To make things clearer, we will

- [ ] Rename `offerRecord.amounts` to `offerRecord.currentAllocation`
- [x] Rename ` zcf.getAmounts` to `zcf.getCurrentAllocations(offerHandles)` and `zcf.getCurrentAllocation(offerHandle) (these are currently in the Sparse Keywords PR https://github.com/Agoric/agoric-sdk/pull/812) 

I (Kate) will rename in the Sparse Keywords PR, but someone can start on the first task on master.

**Comment by DavidBruant** [comment]
With both changes, my understanding is that `currentAllocations` can be acquired by 2 different ways from an `offerHandle`:
- `zoe.getCurrentAllocation(offerHandle)`
- `zoe.getOffer(offerHandle).currentAllocation`

I think it'd be more consistent to only have a single way (i would argue in favor of the first one because it better expresses the fact at the value may change over time)

**Comment by katelynsills** [comment]
In the Sparse Keywords PR #812, we remove `amounts/currentAllocation` from the result of `zcf.getOffer()` as seen by the contract, so after that PR lands, it will not be accessible in two ways in the `contractFacet`. `amounts` still needs to be renamed to `currentAllocation` in the `offerRecord` within Zoe.
