### ISSUE TITLE
How can i get the contract source code from an invite?

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#877]
- From the `invite` payment amount, i can extract the `instanceHandle`
- I can call `zoe.getInstance(instanceHandle)` which gives me the `installationHandle`

But from the `installationHandle`, it's not clear to me how a user can get the contract source code

In any case, going through 2 handles to get to the source code feels like too much for no good reason

Could the source code be made available directly as part of the instanceRecord?

**Comment by katelynsills** [comment]
Somehow we dropped a method on the Zoe service API, which should have been: `zoe.getInstallationRecord(installationHandle)` or `zoe.getInstallation(installationHandle)`. This would return the installation code. This solution would require two calls to get the source code, but I would expect that most of the time, there's no need to look at the source code, since most contracts are reused quite a bit and the only comparison that needs to be made is whether it is an installationHandle you recognize. Let's talk about this more in the design discussion though.
