### ISSUE TITLE
Turning debug diagnostics off should stop doing computation to support them

### ISSUE THREAD

**Issue by FUDCo** [Agoric/agoric-sdk#925]
A classic problem with logging systems that @warner and I observe we now have: a diagnostic message that is gated by a flag still does all the work required to generate the message, even if the flag means that the message isn't actually output, since that work is in a parameter to the logging call and not within the logging system itself.  Our code now has a couple of cases where this might prove important from a performance perspective and it's likely more of these will emerge in the future.  We should come up with a clean, general case solution.

Filing this issue so we don't forget and also to track development of possible solutions.

**Comment by warner** [comment]
Very true. A fun complication is the need for chain-side determinism. We've decided that `console.log()` will strictly ignore its arguments when running on the chain (because any attempt to stringify will allow userspace-controlled code to run, like getters and `.toString` and `Proxy` handlers). We need to establish some debugging patterns and code-style recommendations, something like:
* use `console.log` as you would in any program
* expect to see it print during unit tests, but not on the chain,
* if you use the download-and-run-a-vat-locally tool, your `console.log`s should come back
* if you intentionally sense whether the arguments are stringified, your debug-side execution will differ, and that's your fault

**Comment by FUDCo** [comment]
I believe the new `Fail` template function addresses this.  Closing...
