### ISSUE TITLE
[Zoe] Update types and chainmail for "offer hooks" PR 

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#933]

**Comment by warner** [comment]
FYI https://github.com/Agoric/agoric-sdk/tree/933-zoe-jsdoc is where I'm starting on my changes, only have a few so far.

**Comment by warner** [comment]
Kate told me:

* It is landed in Mark's PR: https://github.com/Agoric/agoric-sdk/commit/c142b7a64e77262927da22bde3af5793a9d39c2a
* Mark's the expert on what changed exactly in that PR - I expect you might have more questions
* main points: seats no longer exist, any method call on a seat in user code is removed because the method call happens automatically when an offer is made, as an offer hook. New helper function inviteAnOffer added to zoeHelpers contractSupport
