### ISSUE TITLE
Contract Host without installations

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#95]
One problem i see with current ERTP is that studying an invite takes to do `host.getInstallationSourceCode(invite.getBalance().installation)` and `invite.getBalance().terms` (this feels a bit awkward to get one part one way and the other part a different way). In [another issue](https://github.com/Agoric/ERTP/issues/179#issuecomment-551044137), i suggest creating a `host~.getInviteContractSourceCodeAndTerms(invite)` method which unifies getting both at the same time

Taking a step back, i'm starting to wonder whether installations are useful at all. I remember that in my first encouter with ERTP, the 2-step process to get a contract started felt weird (`host~.install(source)~.spawn(terms)`), but i took it as granted. With more experience, i'm questionning whether the additional complexity is worth it.

I feel installations could be removed alongside the following changes:
- `host.install(source, terms)` (maybe rename the method to `run` or `start` or `instantiate` or `startContract` something else)
- the invite payment does not carry terms or installation any more. Terms + source are acquired via a new `host~.getInviteContractSourceCodeAndTerms(invite)` method (or any better name)
- check* methods are methods placed directly on the invite payment (on the usage side, this changes `invite.getBalance().installation.check*()` to `invite.getBalance().check*()`)

**Comment by katelynsills** [comment]
I'm going to close this issue for now given that we are [deprecating the contractHost](https://github.com/Agoric/agoric-sdk/issues/95) and reopening it under a new name and design in the future. I think we should open a new issue for that new design.

**Comment by erights** [comment]
Why are we deprecating the contractHost rather than (mostly) just renaming it?

**Comment by katelynsills** [comment]
Copying our [discussion summary here](https://github.com/Agoric/agoric-sdk/issues/394#issuecomment-573217960): 

Just discussed in person and concluded that we should "shelve" contractHost:

1. Rename contractHost to vatSpawner
2. Move vatSpawner and related files to a folder under /test so that we make sure they continuously work with our changes to ERTP but that they are not easily available for users to mistakenly use. Then, when we are ready to make the vatSpawner accessible to users, we can easily do that.
