### ISSUE TITLE
The Date constructor is available in contracts in the fake-chain setup

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#980]
If the `Date` constructor is not meant to be available in blockchains, it shouldn't be available in the fake-chain, because this sets false expectations

I wonder if other things should be disabled. `Math.random`?

I imagine @erights knows

**Comment by erights** [comment]
Is this fake-chain setup within SES?

SES should already be removing `Math.random`.

SES should be disabling the dangerous behavior of `Date` but leave a safe `Date` constructor replacement. The difference is that 
   * `Date.now()` returns `NaN`, 
   * `new Date()`, specifically called with no arguments, returns the equivalent of `new Date(NaN)`, i.e., a date instance that represents an `Invalid Date`,
   * `Date(...)`, the `Date` constructor called as a function, returns the string `'Invalid Date'`.

Having removed the dangerous part, we preserve the `Date` abstraction because it is useful to represent specific dates, to parse and format them, etc.

**Comment by erights** [comment]
Please let me know whether the behavior you're seeing is consistent with this.

**Comment by erights** [comment]
I was wrong about `Math.random`. It is not absent. Rather it is replaced by a function that only throws.

**Comment by michaelfig** [comment]
@DavidBruant would you be able to confirm the above?
