### ISSUE TITLE
Include allegedName in brand-check error message

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#990]
Experience at #986 suggests that the error message for a brand mismatch could be improved

https://github.com/Agoric/agoric-sdk/blob/3f2e4221480135fde740ef92444f2a6a6d81764a/packages/ERTP/src/amountMath.js#L189

The error message could contain `brand.getAllegedName()` and `allegedBrand.getAllegedName()`

---

Unrelated, but why is the test `mustBeSameStructure` and not `brand === allegedBrand`? I would have imagined the brand is useful for its object identity and it'd make for a more readable and quicker test

**Comment by katelynsills** [comment]
That is a good question. I think I had that identity check originally, but @erights dissuaded me and now I can't remember why. Looking at the code in `mustBeSameStructure` I think for a brand, it always bottoms out in identity equality anyways:

```
switch (leftStyle) {
    case 'null':
    case 'undefined':
    case 'string':
    case 'boolean':
    case 'number':
    case 'symbol':
    case 'bigint':
    case 'presence': {
      if (!sameValueZero(left, right)) {
        complain('different');
      }
      break;
    }
....
export function sameValueZero(x, y) {
  return x === y || Object.is(x, y);
}
```

**Comment by erights** [comment]
FWIW I don't remember dissuading you, though I think I can reconstruct what my reasons were:

`===` among objects tests if the two operands are the same JS object, at the JS level of abstraction. Here we want to test whether they are the same at the level of abstraction of our distributed object system. Were this field to change from holding an identity-based object `x` to holding a pass-by-copy container holding that object `harden([x])`, then `===` would break across that refactoring but `*sameStructure` would still do the right thing.

In any case, for this code I no longer object to using `===`.

**Comment by katelynsills** [comment]
> FWIW I don't remember dissuading you

I could certainly be misremembering :) Thanks for the explanation!

**Comment by katelynsills** [comment]
Just tried and the error message probably can't include `brand.getAllegedName()` and `allegedBrand.getAllegedName()` because both brands might be remote. We can't do an eventual-send and wait on the response, either, because that will put us at the mercy of the creator of the remote brands. I will improve the message overall though

**Comment by erights** [comment]
Attn @michaelfig because we will eventually be able to include frozen descriptions on the presences.

**Comment by erights** [comment]
See #804 for the plan to enhance presences

**Comment by DavidBruant** [comment]
Following up on the comment in the PR: https://github.com/Agoric/agoric-sdk/pull/1000#pullrequestreview-400399187

I think #990 should remain open, because the error message being generic was a cause of wasted hours that would have been saved if the messages contained the alleged brand names
I acknoledge the current technical limitations preventing the alleged brand names being part of the error messages, but there is a plan for this limitation to go away eventually, so there's hope for this issue (after #804 )

**Comment by katelynsills** [comment]
Ok, I'm ok with this remaining open if there is a fix in the near term. If there was not a fix, I would want to close it with an explanation of why. 

I would expect users to look in both closed and open issues to see if anything relating to their problem already exists, so I think that users still see closed issues, and closed issues are generally ok as long as the reason for closing is explained. (I'm not referring to "closed because stale" situations.) IMO, issues should be closed as soon as possible to keep the number of open issues small so the issues are nearly all actionable. Open issues should be work items, in my view.

**Comment by katelynsills** [comment]
@erights, given that the alleged name is now part of the error logging, should this be closed?

**Comment by erights** [comment]
Yup, thanks. Closing.

**Comment by katelynsills** [comment]
> Yup, thanks. Closing.

Woohoo! This was a big one
